### ISSUE TITLE
UA translate

### ISSUE THREAD

**Issue by panikajo** [J-Tanzanite/Little-Anti-Cheat#10]
https://github.com/panikajo/ua_translate_lilac/blob/master/lilac.phrases.txt

**Comment by J-Tanzanite** [comment]
Nice!

Just one question, shouldn't it be "ua" and not "ru"?
```
"welcome_msg"
{
	"#format"	"{1:s}"
	"ru"		"Цей сервер захищений Little Anti-Cheat {1}"
}
```
should be:
```
"welcome_msg"
{
	"#format"	"{1:s}"
	"ua"		"Цей сервер захищений Little Anti-Cheat {1}"
}
```

Also, one last thing.
May I credit you for the translations in the translations credits? And would you like a link to your github or steam profile?

**Comment by panikajo** [comment]
> Nice!
> 
> Just one question, shouldn't it be "ua" and not "ru"?
> 
> ```
> "welcome_msg"
> {
> 	"#format"	"{1:s}"
> 	"ru"		"Цей сервер захищений Little Anti-Cheat {1}"
> }
> ```
> 
> should be:
> 
> ```
> "welcome_msg"
> {
> 	"#format"	"{1:s}"
> 	"ua"		"Цей сервер захищений Little Anti-Cheat {1}"
> }
> ```
> 
> Also, one last thing.
> May I credit you for the translations in the translations credits? And would you like a link to your github or steam profile?
yeah, sorry my bad.
i change ru to ua in github.

**Comment by J-Tanzanite** [comment]
Alright, I've added your translations and given you credit :)
