### ISSUE TITLE
anti dll

### ISSUE THREAD

**Issue by alix1383** [J-Tanzanite/Little-Anti-Cheat#117]
add anti dll and fix it if possible
[anti dll](https://github.com/JDW1337/AntiDLL)

**Comment by azalty** [comment]
Fix what?

Why should AntiDLL be bundled with LilAC? They are two separate projects.

**Comment by sapphonie** [comment]
AntiDLL doesn't seem to make sense with TF2, I got it working and clients listen to differing numbers of game events seemingly randomly, and cheat clients don't seem to have any bearing on the number of events that are listened to.

**Comment by J-Tanzanite** [comment]
As @sapphonie points out, wouldn't work in TF2...

However, I don't really see myself working on AntiDLL for multiple source games.
And AntiDLL and Lilac are very different from each other, and I don't think they would mix well in a single plugin.

It seems far more sensible to keep them separated, and for server owners to install both if they so choose.

**Comment by J-Tanzanite** [comment]
I've decided to close this, to keep things tidy and neat.
Thanks for the suggestion anyway :)
