### ISSUE TITLE
[REQ] Messages for admin in chat 

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#121]
The same as SMAC, it was sending a message to admin only in chat about what is happening if there is a detection.
"Player is suspected of using an aimbot (detection 2)" ect

**Comment by J-Tanzanite** [comment]
I guess that could be done, I wouldn't make the chat messages filled with a lot of details tho, and I would probably only tell admins in chat on the 3rd detection and so on.
But sure, nice idea :)

**Comment by lunatixxx** [comment]
In game warning for macro is not working if you have set detection on log only, you absolutely have to kick at minimum ?

**Comment by azalty** [comment]
> In game warning for macro is not working if you have set detection on log only, you absolutely have to kick at minimum ?

Yes

**Comment by J-Tanzanite** [comment]
Closing this, as this was added in the [development branch](https://github.com/J-Tanzanite/Little-Anti-Cheat/tree/development), this will get pushed into the master branch in the future.
