### ISSUE TITLE
Idea: Check player movement flags before testing for Bhop.

### ISSUE THREAD

**Issue by Rushaway** [J-Tanzanite/Little-Anti-Cheat#129]
To prevent false flag, check if the players is using a ladder before counting the bhop ?

if (GetEntityMoveType(client) != MOVETYPE_LADDER )

**Comment by J-Tanzanite** [comment]
Out of curiosity, do you know of a case where not doing so would lead to problems?

**Comment by Rushaway** [comment]
I have no idea except for Ladder, But i will say : 

- MOVETYPE_FLY & MOVETYPE_FLYGRAVITY (like in surf map)
- MOVETYPE_NOCLIP
- MOVETYPE_LADDER

MOVETYPE_PUSH (need to be tested, trigger push can increase drasticly velocity, can make false flag aswell?)

**Comment by lunatixxx** [comment]
There are some false bhop detections (with macro) on left 4 dead 2 when ceiling is not high and you jump quickly against it.

**Comment by J-Tanzanite** [comment]
> There are some false bhop detections (with macro) on left 4 dead 2 when ceiling is not high and you jump quickly against it.

The Development branch has updated Bhop detection to consider time spent in air, give that a try.

**Comment by Rushaway** [comment]
After some test all MOVETYPE I listed are correct.

**Comment by J-Tanzanite** [comment]
> Out of curiosity, do you know of a case where not doing so would lead to problems?

I should probably clarify what I meant by this.
I wasn't asking about other flags, I was asking if you knew of a scenario where not checking player movement-flags at all, would lead to false positives.
I don't quite see a reason to add a check if it serves no purpose.

**Comment by J-Tanzanite** [comment]
I'm closing this, as no further replies have been made.
Again, if someone can show how not checking movement flags can cause issues, then please reply to this with steps on what to do.
