### ISSUE TITLE
Enabling sourcebans+ break bans

### ISSUE THREAD

**Issue by lunatixxx** [J-Tanzanite/Little-Anti-Cheat#130]
Did not have any problem before. Pretty sure it is trying to translate the ban reason from message "[SM] Player was banned by console (reason: ---)" to everyone on the server in chat and that is the reason it breaks.

L 08/11/2022 - 04:28:11: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 08/11/2022 - 04:28:11: [SM] Blaming: lilac.smx
L 08/11/2022 - 04:28:11: [SM] Call stack trace:
L 08/11/2022 - 04:28:11: [SM]   [0] Format
L 08/11/2022 - 04:28:11: [SM]   [1] Line 211, extra/lilac_stock.sp::lilac_ban_client
L 08/11/2022 - 04:28:11: [SM]   [2] Line 339, extra/lilac_aimbot.sp::lilac_detected_aimbot
L 08/11/2022 - 04:28:11: [SM]   [3] Line 282, extra/lilac_aimbot.sp::timer_check_aimbot

L 08/11/2022 - 04:17:47: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 08/11/2022 - 04:17:47: [SM] Blaming: lilac.smx
L 08/11/2022 - 04:17:47: [SM] Call stack trace:
L 08/11/2022 - 04:17:47: [SM]   [0] Format
L 08/11/2022 - 04:17:47: [SM]   [1] Line 209, extra/lilac_stock.sp::lilac_ban_client
L 08/11/2022 - 04:17:47: [SM]   [2] Line 150, extra/lilac_bhop.sp::lilac_ban_bhop
L 08/11/2022 - 04:17:47: [SM]   [3] Line 78, extra/lilac_bhop.sp::check_bhop_max
L 08/11/2022 - 04:17:47: [SM]   [4] Line 50, extra/lilac_bhop.sp::lilac_bhop_check
L 08/11/2022 - 04:17:47: [SM]   [5] Line 348, plugin.sp::OnPlayerRunCmd

**Comment by lunatixxx** [comment]
// Ban reason language.
// 0 = Use server's language.
// 1 = Use the language of the cheater.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
lilac_ban_language "1"

**Comment by azalty** [comment]
What version are you running? Try updating.

**Comment by lunatixxx** [comment]
No i have the last version with updated files. By the way there were two cheaters and both were logged in the file with multiple detection, the error only happened at the moment to ban them so it failed and they could continue to play on server. 
So i if they did got logged i honestly doubt that is some sort of bypassk, and considering that i had no problems with base bans my theory of the translation bug seems more realistic. 

I already had the same type of error when i tried to translate boss_vote plugin, so i had to found a roundabout way to do it.

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies.

**Comment by mrdiega** [comment]
```
L 03/19/2023 - 19:18:04: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 03/19/2023 - 19:18:04: [SM] Blaming: lilac.smx
L 03/19/2023 - 19:18:04: [SM] Call stack trace:
L 03/19/2023 - 19:18:04: [SM]   [0] Format
L 03/19/2023 - 19:18:04: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 03/19/2023 - 19:18:04: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 03/19/2023 - 19:18:04: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
```
[Lilac] Little Anti-Cheat (1.7.4) by J_Tanzanite
Material Admin (0.8.6-ae3f5b9) by Material Admin Dev Team
game: css v92

**Comment by J-Tanzanite** [comment]
> ```
> L 03/19/2023 - 19:18:04: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
> L 03/19/2023 - 19:18:04: [SM] Blaming: lilac.smx
> L 03/19/2023 - 19:18:04: [SM] Call stack trace:
> L 03/19/2023 - 19:18:04: [SM]   [0] Format
> L 03/19/2023 - 19:18:04: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
> L 03/19/2023 - 19:18:04: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
> L 03/19/2023 - 19:18:04: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
> ```
> 
> [Lilac] Little Anti-Cheat (1.7.4) by J_Tanzanite Material Admin (0.8.6-ae3f5b9) by Material Admin Dev Team game: css v92
---
Did you install the latest translations? You'll need those.

Also, CSS v92 is __not supported__, you can try to use Lilac, but be aware there may be issues.
Make sure you've set these ConVars like so:
```
lilac_angles 0
lilac_angles_patch 0
```
