### ISSUE TITLE
Idea : SourceBans and Autoshoot

### ISSUE THREAD

**Issue by ShyperOne** [J-Tanzanite/Little-Anti-Cheat#131]
Можете добавить старую версию SourceBans?
Ссылка - https://disk.yandex.ru/d/jfLRXZ9aXYxCuA

И ещё одно. На мышках, например, bloody есть двойной/тройной клик. Autoshoot ругается на это. Поправите?

**Comment by shockpast** [comment]
title: english
description: russian

**Comment by J-Tanzanite** [comment]
Sure, I can look into adding sourcebans, we have an other issue for it [here](https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/134). :)

As for autoshoot, I sadly do not understand what you mean.
I also recommend using [GoogleTranslate](https://translate.google.com) and translating messages into English, makes it easier to work. :)

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies and further clarification.
Sourcebans will be added however :)
