### ISSUE TITLE
I found a hacker software which could escape LAC detection in L4D2

### ISSUE THREAD

**Issue by honghl5** [J-Tanzanite/Little-Anti-Cheat#132]
If I provide the hacker software which can escape detection of LAC, is that helpful for LAC development?

The hacker in my hand can escape anti-wallhack. The user can see SI through walls without detection.

I dont know whether it is helpful or not. just let you know.

**Comment by J-Tanzanite** [comment]
Lilac never had wallhack detection, afaik, no server side AC does.
I think what you mean is wallhack blocking, which Lilac also doesn't have.

**Comment by J-Tanzanite** [comment]
Closing this as this is a discussion on anti-wallhacks, a feature that doesn't exist in Lilac, if you have other questions in the future, don't hesitate to let me know :)
