### ISSUE TITLE
Add Sourcebans support (Not Sourcebans++)

### ISSUE THREAD

**Issue by denzel519** [J-Tanzanite/Little-Anti-Cheat#134]
Is it possible to add check sourcebans to lilac, otherwise there is only sourcebans++

**Comment by J-Tanzanite** [comment]
Possible yes, I just don't quite see why people wouldn't just update to SB++.
That said, I don't mind adding sourcebans in a future update, unless there's a technical problem or security issue with doing so.

**Comment by denzel519** [comment]
We just have sb modified for the site. If you add it would be great. Thanks

**Comment by J-Tanzanite** [comment]
> We just have sb modified for the site. If you add it would be great. Thanks

What do you mean?

**Comment by denzel519** [comment]
> > We just have sb modified for the site. If you add it would be great. Thanks
> 
> What do you mean?

The fact that sb suits us than sb ++

**Comment by J-Tanzanite** [comment]
Ahh, I see what you mean.
Yeah I'll add this to my todo list, granted no conflicts arise, this is fine. :)
Currently busy with some IRL stuff, but will be on it once everything settles

**Comment by denzel519** [comment]
> Ahh, I see what you mean. Yeah I'll add this to my todo list, granted no conflicts arise, this is fine. :) Currently busy with some IRL stuff, but will be on it once everything settles

There will be no problems with sb, we replaced sb++ with sb in the source codes and everything works with a bang. Just to avoid updating the sources with updates every time if you can add it initially. Thanks

**Comment by Rushaway** [comment]
@denzel519 To be sure we talk about https://github.com/GameConnect/sourcebansv1 ?

**Comment by denzel519** [comment]
> @denzel519 To be sure we talk about https://github.com/GameConnect/sourcebansv1 ?

Well, you have sourcebanspp, you just need to add sourcebans and everything will work.

26th line|
#tryinclude <sourcebans>
-———————————————————-
41 lines|
#if !defined _sourcebans_included
  #warning "sourcebans.inc" include file not found, banning though SourceBans++ will not work!
#endif
———————————————————-
Line 215|
sourcebanspp_exist = LibraryExists("sourcebans");
———————————————————-
lines 239-255 |
public void OnLibraryAdded(const char []name)
{
  if (StrEqual(name, "sourcebans"))
    sourcebanspp_exist = true;
  else if (StrEqual(name, "materialadmin"))
    materialadmin_exist = true;
  else if (StrEqual(name, "updater"))
    lilac_update_url();
}
public void OnLibraryRemoved(const char []name)
{
  if (StrEqual(name, "sourcebans"))
    sourcebanspp_exist = false;
  else if (StrEqual(name, "materialadmin"))
    materialadmin_exist = false;
}
well, in the included lil
in lilac_globals.sp, lilac_stock.sp
from SBPP_BanPlayer to SBBanPlayer
———————————————————-

**Comment by Rushaway** [comment]
Can be close. 1.7.4 add a support for it. 
https://github.com/J-Tanzanite/Little-Anti-Cheat/tree/development
