### ISSUE TITLE
l4d2 Wrong detected.

### ISSUE THREAD

**Issue by a847427933** [J-Tanzanite/Little-Anti-Cheat#137]
While using minigun to shoot it will cause Angle-Cheats detected and get ban~
Idk it will cause in the official map or not. but it will be triggered in the third-party map.

**Comment by J-Tanzanite** [comment]
Could you be more specific? What map and where on the map?

**Comment by a847427933** [comment]
> Could you be more specific? What map and where on the map?

IDK what map is, i will check after work and upload a video to youtube.

**Comment by J-Tanzanite** [comment]
Any updates?

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies.
