### ISSUE TITLE
New line before print a new log

### ISSUE THREAD

**Issue by Rushaway** [J-Tanzanite/Little-Anti-Cheat#141]
We have a massive logs file from lilac with more than 80k of lines.
It's a mess to read them bcs sometimes it print the log on the same line..

`2022/10/21 02:06:47 [Version 1.7.3] {Name: "Info" | SteamID: STEAM_0:1:8787915 | IP: 000.00.32.71} was detected of using Macro Auto-Jump (Detection: 4 | Max p2022/10/21 16:31:52 [Version 1.7.3] {Name: "hyper" | SteamID: STEAM_0:1:232208592 | IP: 000.00.210.174} is suspected of using Bhop (Detection: 2 | Bhops: 7 | JumpTicks: 38).`

Adding a new line should do the trick?

**Comment by J-Tanzanite** [comment]
Lilac uses `WriteFileLine()` to write a line to the file, this automatically adds a newline.
It's supposed to format `%s was detected of using Macro %s (Detection: %d | Max presses: %d).` this and write a line to the logs, but yours get cut off at `Max p(resses)`.

I'm not sure why you're getting this effect, as it should finish writing the macro detection to the logs before proceeding to write the Bhop detection. And it's particularly odd that it's written on the same line.

I can't see any issues with the code in Lilac, and honestly, it seems to be a bug with SM?
If you're using an old version of SourceMod or MM:S, then try updating.

**Comment by J-Tanzanite** [comment]
Any updates on this?

**Comment by crashzk** [comment]
Just for feedback, here everything is normal, it always skips a line for a new detection.
```
05/01/2023 | 21:16:18 [Version 1.7.3] {Name: "n" | SteamID: STEAM_1:0:43173994 | IP: 000.00.000.007} was detected of using Macro Auto-Jump (Detection: 2 | Max presses: 20).
	Pos={-9575,9758,19}, Angles={43.09805,59.10007,0.00000}, Map="am_dust1999", Team={2}, Weapon="weapon_ak47", Latency={Inc:0.000420,Out:0.037411}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.130540,Out:0.000000}, ConnectionTime={574.539062 seconds}, GameTime={1440.835937 seconds}
05/01/2023 | 21:16:20 [Version 1.7.3] {Name: "n" | SteamID: STEAM_1:0:43173994 | IP: 00.00.000.017} was detected of using Macro Auto-Jump (Detection: 3 | Max presses: 20).
	Pos={-9452,9625,-87}, Angles={31.94397,-27.23995,0.00000}, Map="am_dust1999", Team={2}, Weapon="weapon_ak47", Latency={Inc:0.000407,Out:0.038122}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.073890,Out:0.000000}, ConnectionTime={576.125000 seconds}, GameTime={1442.421875 seconds}
05/01/2023 | 21:19:35 [Version 1.7.3] {Name: "n" | SteamID: STEAM_1:0:43173994 | IP: 100.00.000.117} was detected of using Macro Auto-Jump (Detection: 3 | Max presses: 20).
	Pos={-2753,2476,1}, Angles={35.11196,-45.71991,0.00000}, Map="am_dust1999", Team={3}, Weapon="weapon_ak47", Latency={Inc:0.000410,Out:0.038019}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.036914,Out:0.000000}, ConnectionTime={771.507812 seconds}, GameTime={1637.804687 seconds}
05/01/2023 | 21:19:53 [Version 1.7.3] {Name: "n" | SteamID: STEAM_1:0:43173994 | IP: 007.003.00.000} was detected of using Macro Auto-Jump (Detection: 4 | Max presses: 20).
	Pos={-2739,2482,1}, Angles={27.65399,8.94009,0.00000}, Map="am_dust1999", Team={3}, Weapon="weapon_knife", Latency={Inc:0.000412,Out:0.038469}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.019927,Out:0.000000}, ConnectionTime={789.210937 seconds}, GameTime={1655.507812 seconds}
```
SM & MM on the latest versions of the stable branch.
