### ISSUE TITLE
v1.7.4 error loading

### ISSUE THREAD

**Issue by oleg35hp** [J-Tanzanite/Little-Anti-Cheat#145]
[SM] Unable to load plugin "lilac.smx": Required extension "TF2 Tools" file("game.tf2.ext") not running

#undef REQUIRE_EXTENSIONS
should be added before including tf2 stuff

**Comment by J-Tanzanite** [comment]
I wish I could just update the release to the new files, sadly I can't, and had to re-release the release... lmao.

Fixed, and should work now.

**Comment by azalty** [comment]
> I wish I could just update the release to the new files, sadly I can't, and had to re-release the release... lmao.

Delete the attachment, confirm changes. Edit the release, add the new attachment, confirm changes. Unfortunately you can't remove and  upload a file that has the same name in one go.
