### ISSUE TITLE
Players blink. Anti WH?

### ISSUE THREAD

**Issue by rustov** [J-Tanzanite/Little-Anti-Cheat#153]
After installing Lilac, I noticed that the players began to appear from behind the walls with a delay, as if blinking. How to fix it? What parameter is responsible for this? Looks like a typical anti WH.

CS:GO, Lilac 1.7.3

**Comment by J-Tanzanite** [comment]
Little Anti-Cheat does not have an Anti-Wallhack feature, the issue you're having is unlikely to be with Lilac.

If you're running SMAC with its Anti-Wallhack module, just keep in mind that it doesn't always work correctly with CS:GO.

**Comment by rustov** [comment]
> Little Anti-Cheat does not have an Anti-Wallhack feature, the issue you're having is unlikely to be with Lilac.
> 
> If you're running SMAC with its Anti-Wallhack module, just keep in mind that it doesn't always work correctly with CS:GO.

You're right. sorry. That was my too tight occlusion margin settings (cs go has a built-in full anti-wh)
