### ISSUE TITLE
[Request] Discord Support

### ISSUE THREAD

**Issue by Rushaway** [J-Tanzanite/Little-Anti-Cheat#154]
It will awesome if Lilac support Discord API. (https://github.com/Sarrus1/DiscordWebhookAPI)
When detecting a someone (call in same time as lilac_warn_admins)

**Comment by Rushaway** [comment]
@NaathySz Yeah. Sure ! :)

**Comment by NaathySz** [comment]
> @NaathySz Yeah. Sure ! :)

https://github.com/J-Tanzanite/Little-Anti-Cheat/pull/155
Waiting @J-Tanzanite now.

**Comment by J-Tanzanite** [comment]
I would love to support Discord alerts, but there appears to be several Discord APIs available, so it would make sense for such support to come from a third party plugin, rather than from Lilac itself.
I'll happily look further into this.

**Comment by NaathySz** [comment]
Ofc, what i did is just add forwards, so i release the plugin to pass detections to Discord.

**Comment by Nerus87** [comment]
Yeah, you should use/include only handlers for these things on Lilac, but not create another extension/API (dependency) to support, so I can fully agree this should be done as a Third-party plugin/ext.
