### ISSUE TITLE
sm 1.11 can you remove warnings?

### ISSUE THREAD

**Issue by maclarens** [J-Tanzanite/Little-Anti-Cheat#156]
Compiling lilac...
SourcePawn Compiler 1.11.0.6927
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

lilac/lilac_string.sp(115) : warning 242: function "event_namechange" should return an explicit value
lilac/lilac_string.sp(115) : warning 242: function "event_namechange" should return an explicit value
lilac/lilac_stock.sp(307) : warning 242: function "timer_kick" should return an explicit value
lilac/lilac_ping.sp(19) : warning 224: user warning: Messy code!

lilac/lilac_noisemaker.sp(37) : warning 242: function "event_inventoryupdate" should return an explicit value
lilac/lilac_macro.sp(194) : warning 242: function "timer_decrement_macro" should return an explicit value
lilac/lilac_convar.sp(19) : warning 224: user warning: Messy code! Considering re-writing this entire system.

lilac/lilac_config.sp(481) : warning 242: function "lilac_date_list" should return an explicit value
lilac/lilac_bhop.sp(161) : warning 242: function "timer_decrement_bhop" should return an explicit value
lilac/lilac_bhop.sp(161) : warning 242: function "timer_decrement_bhop" should return an explicit value
lilac/lilac_aimlock.sp(262) : warning 242: function "timer_decrement_aimlock" should return an explicit value
lilac/lilac_aimlock.sp(262) : warning 242: function "timer_decrement_aimlock" should return an explicit value
lilac/lilac_aimbot.sp(143) : warning 242: function "timer_check_aimbot" should return an explicit value
lilac/lilac_aimbot.sp(143) : warning 242: function "timer_check_aimbot" should return an explicit value
lilac/lilac_aimbot.sp(371) : warning 242: function "timer_decrement_aimbot" should return an explicit value
lilac/lilac_aimbot.sp(371) : warning 242: function "timer_decrement_aimbot" should return an explicit value
lilac.sp(282) : warning 242: function "event_teleported" should return an explicit value
lilac.sp(298) : warning 242: function "timer_welcome" should return an explicit value
Code size:         112736 bytes
Data size:         759320 bytes
Stack/heap size:      49092 bytes
Total requirements:  921148 bytes

18 Warnings.
mac2s@hellstar:~$ Compiling lilac...
lilac/lilac_stock.sp(307) : warning 242: function "timer_kick" should return an explicit value
lilac/lilac_ping.sp(19) : warning 224: user warning: Messy code!

lilac/lilac_noisemaker.sp(37) : warning 242: function "event_inventoryupdate" should return an explicit value
lilac/lilac_macro.sp(194) : warning 242: function "timer_decrement_macro" should return an explicit value
lilac/lilac_convar.sp(19) : warning 224: user warning: Messy code! Considering re-writing this entire system.

lilac/lilac_config.sp(481) : warning 242: function "lilac_date_list" should return an explicit value
lilac/lilac_bhop.sp(161) : warning 242: function "timer_decrement_bhop" should return an explicit value
lilac/lilac_bhop.sp(161) : warning 242: function "timer_decrement_bhop" should return an explicit value
lilac/lilac_aimlock.sp(262) : warning 242: function "timer_decrement_aimlock" should return an explicit value
lilac/lilac_aimlock.sp(262) : warning 242: function "timer_decrement_aimlock" should return an explicit value
lilac/lilac_aimbot.sp(143) : warning 242: function "timer_check_aimbot" should return an explicit value
lilac/lilac_aimbot.sp(143) : warning 242: function "timer_check_aimbot" should return an explicit value
lilac/lilac_aimbot.sp(371) : warning 242: function "timer_decrement_aimbot" should return an explicit value
lilac/lilac_aimbot.sp(371) : warning 242: function "timer_decrement_aimbot" should return an explicit value
lilac.sp(282) : warning 242: function "event_teleported" should return an explicit value
lilac.sp(298) : warning 242: function "timer_welcome" should return an explicit value
Code size:         112736 bytes
Data size:         759320 bytes
Stack/heap size:      49092 bytes
Total requirements:  921148 bytes

**Comment by J-Tanzanite** [comment]
Done in latest update :)
