### ISSUE TITLE
when i was testing if the lilac installed, i banned myself

### ISSUE THREAD

**Issue by leopoldfitzgithub** [J-Tanzanite/Little-Anti-Cheat#157]
how to unban myself? is there a banlist?

**Comment by J-Tanzanite** [comment]
Depends on how you setup your server, I'm assuming you didn't install Sourcebans and setup a server for it, so most likely you're just banned with basebans.

You could try this command on the server console:
```sm_unban STEAMID```
Replace ```STEAMID``` with your SteamID, you can find it here: https://steamid.io/ by inserting the link to your steam profile.
As far as I know, steamID, steamID3 and steamID64 should all work with this command.

If that doesn't work, you can edit the file ```cfg/banned_user.cfg``` on the server remotely and remove your SteamID, and then restart the server.
