### ISSUE TITLE
[Question] Add immunity for high ping

### ISSUE THREAD

**Issue by TheMrEvgen** [J-Tanzanite/Little-Anti-Cheat#16]
Will I add an imunnitet for high ping?

**Comment by J-Tanzanite** [comment]
I thought about it, and sadly, no.

Currently, the way Lilac provides immunity to cheat detections is via the use of "forwards".
Like so:
``` c
public Action lilac_allow_cheat_detection(int client, int cheat)
```
And its purpose is so other plugins can tell Lilac to ignore a cheat detection if they've been messing with the Anti-Cheat's ability to detect something, like Bhop.

Adding a forth "forward" for misc features seems a little overkill; especially for high ping.
So currently, I have no intentions of adding immunity for misc features.
