### ISSUE TITLE
Using latest TF2Classic Tools (Both TF2C official fork and original version) throws an compile error

### ISSUE THREAD

**Issue by RoonMoonlight** [J-Tanzanite/Little-Anti-Cheat#163]
The [TF2C Team fork version](https://github.com/tf2classic/SM-TF2Classic-Tools) and [original version](https://github.com/Scags/TF2Classic-Tools) throws same error, which is following:
```
error 017: undefined symbol "TF2_GetResourceEntity"
error 017: undefined symbol "TF2_GetResourceEntity"
error 017: undefined symbol "GetPlayerWeaponSlot"
error 017: undefined symbol "RemovePlayerItem"
error 017: undefined symbol "AcceptEntityInput"
```

Created seperate issue from [this pull request](https://github.com/J-Tanzanite/Little-Anti-Cheat/pull/162).

**Comment by J-Tanzanite** [comment]
I think this issue should be on their repo.

I wasn't able to compile on Sourcemod version 1.11, but 1.10 did work for me.
If you are also able to compile in SM version 1.10, then perhaps this should be mentioned in the comments in your PR? :)

**Comment by RoonMoonlight** [comment]
Okay, it works when SM 1.10 is used, so I will go add that information
