### ISSUE TITLE
lilac_bhop cannot be set to negative value (log only)

### ISSUE THREAD

**Issue by theletterjwithadot** [J-Tanzanite/Little-Anti-Cheat#164]
I'm currently only wanting to log bhop and not ban them. I have lilac_bhop in lilac_config.cfg set to -1 (as it's stated that negative value = log only).
```
// Bhop detection mode (Negative values = log-only).
// 0 = Disabled.
// 1&2 = Reserved (Invalid).
// 3 = Custom (unlocks lilac_bhop_set command).
// 4 = Low.
// 5 = Medium.
// 6 = High.
// -
// Default: "5"
// Minimum: "-6.000000"
// Maximum: "6.000000"
lilac_bhop "-1"
```

I noticed players still getting banned for bhop and I went to do some checks.

The value in server was:
```
lilac_bhop
"lilac_bhop" = "5" min. -6.000000 max. 6.000000
 - Bhop detection mode (Negative values = log-only).
0 = Disabled.
1&2 = Reserved (Invalid).
3 = Custom (unlocks lilac_bhop_set command).
4 = Low.
5 = Medium.
6 = High.
```

I tried to manually set in server to -1 however I'm greeted with the warning message and lilac_bhop stays at 5:
```
lilac_bhop -1
[Lilac] Warning: Bhop mode 1 & 2 has been disabled, setting Bhop mode to 5 (Medium).
Current Bhop values:
    Type  : Min possible : Current
    Min   :  5           : 7
    Ticks : -1           : -1
    Max   : 10           : 20
    Air   :  0           : 31
    Total :  1           : 3
Current Bhop values:
    Type  : Min possible : Current
    Min   :  5           : 7
    Ticks : -1           : -1
    Max   : 10           : 20
    Air   :  0           : 31
    Total :  1           : 3
```

Please advise.

**Comment by J-Tanzanite** [comment]
As stated in the config:
> 1&2 = Reserved (Invalid).

These two numbers are invalid (positive or negative), and attempting to use them will automatically put you in the recommended mode (5).

However, as you've discovered, there is an oversight: Using the invalid modes in log-only _should_ put you in the log-only version of the recommended mode (-5), but it doesn't... That is an oversight on my part.

That said, don't use mode 1 & 2, they're invalid (Forever).
Use: -4, -5 or -6 to only log. I recommend using -5 for your purpose.

I'll fix oversight later; thanks for reporting this 👍

**Comment by theletterjwithadot** [comment]
Ah! I get how the “negative value” works now.
Wrong of me to assume the negative value meant the same as the other cvars where it states “// -1 = Log only”.

Thanks for the clarification! Have set it to -5 now and it reflects correctly as -5 now. 😄
