### ISSUE TITLE
A bind that triggers the anticheat

### ISSUE THREAD

**Issue by stefanx111** [J-Tanzanite/Little-Anti-Cheat#165]
Hi! This bind trigger aim lock. 
When the suspect hits someone and uses the bind at the same time, the anti-cheat detects that he have aim lock

alias "+spinbot" "sensitivity 10; m_yaw 666"
alias "-spinbot" "sensitivity 1.7; m_yaw 0.022"
bind q "+spinbot"

![Screenshot_2](https://user-images.githubusercontent.com/60297289/214904449-855dad0e-4ad1-43ff-9fac-c75d1381c115.png)

**Comment by J-Tanzanite** [comment]
Long version, answered here https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/84 and here https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/86

Short version: Cheats can do perfect 180 turns when aimbotting, humans cannot turn that accurately in normal play.
If someone decides to go _out of their way_ to use special commands or binds (Or anything else abnormal you can't do by accident) to _mimic cheaters_, then it's their own fault when they get banned. :') 

This can't be fixed (without making a bypass method easy for cheats), and there's not really anything to fix, Lilac made the right determination: This player is not aiming in a human way.

If someone complains about a false ban, and claim they did this, you should look at the demo of their game to make sure they were only doing 180 spins and not other types of aimbot; and then unban and tell them not to do it again.

**Comment by stefanx111** [comment]
Thanks, I didn't see that it was discussed before.
