### ISSUE TITLE
lilac_forward_client_cheat issue

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [J-Tanzanite/Little-Anti-Cheat#167]
lilac_forward_client_cheat is being called before the line is properly formatted, this causes the lilac_cheater_detected forward to contain an incorrect line

https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/v1.7.1/scripting/lilac/lilac_aimbot.sp#L296

**Comment by J-Tanzanite** [comment]
Sorry, but I am not sure I understand what you mean.
The line that gets logged has nothing to do with the forwards, no line is included in the forwards.

**Comment by BrutalCSEjziponken** [comment]
> Sorry, but I am not sure I understand what you mean. The line that gets logged has nothing to do with the forwards, no line is included in the forwards.

https://media.discordapp.net/attachments/812053761547567124/1071984386980982854/image.png

What about that line? xD

**Comment by J-Tanzanite** [comment]
> > Sorry, but I am not sure I understand what you mean. The line that gets logged has nothing to do with the forwards, no line is included in the forwards.
> 
> https://media.discordapp.net/attachments/812053761547567124/1071984386980982854/image.png
> 
> What about that line? xD

I'm sorry, that doesn't exist in the official version of Lilac, and never has?
Main branch: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/scripting/lilac/lilac_stock.sp#L434
Development branch: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/development/scripting/lilac/lilac_stock.sp#L434

Adding line info was however suggested by people who wanted more info about detections in forwards, however I've suggested (and planned) to instead create a native for obtaining more information about detections.

**Comment by J-Tanzanite** [comment]
I guess I'll close this due to lack of replies.
Discord support will be done in its own plugin by others once I get the native implemented.
