### ISSUE TITLE
Bhop ban.

### ISSUE THREAD

**Issue by adyshark** [J-Tanzanite/Little-Anti-Cheat#173]
I have vip players that using bunnyhop on my server, but still get banned even if lilac_ban is set to not take action. I tried all values for bhop -1, 0, still gets ban.

**Comment by J-Tanzanite** [comment]
Version of Lilac?
Game?

`lilac_bhop` doesn't use 1 & 2 btw, it says so in the config file:
```
Bhop detection mode (Negative values = log-only).
0 = Disabled.
1&2 = Reserved (Invalid).
3 = Custom (unlocks lilac_bhop_set command).
4 = Low.
5 = Medium.
6 = High.
```

`5` is the recommended value.

As for VIP, the solution there is to add this code https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/1#issuecomment-614134149 into the BHOP plugin (not Lilac).
You should probably contact the VIP Bhop plugin author for that.
