### ISSUE TITLE
Bhop ban length

### ISSUE THREAD

**Issue by Truyn** [J-Tanzanite/Little-Anti-Cheat#174]
![image](https://user-images.githubusercontent.com/53527324/232329465-3c9e748f-5dc7-48f0-a6a6-802c861a1a25.png)

Add changes to the length of the ban for bhop and macros to the settings
Thx

**Comment by J-Tanzanite** [comment]
Hi ^-^
This option exists as a command: `lilac_set_ban_length`.

To change the ban length for any specific cheat feature, can be done like so:
`lilac_set_ban_length bhop 30` - Sets ban length for Bhop to 30 minutes.

You can add this command to the bottom of the Lilac config file.
The only restriction to this command is for Macros, where bans cannot be longer than 60 minutes or shorter than 15.

...
Given that this is a command and not a ConVar, it's not really well documented anywhere...
I should try to fix that somehow, so it's more clear; thanks for the headsup.

**Comment by J-Tanzanite** [comment]
Closing due to lack of replies, hopefully the answer I gave above solved your issue, feel free to reopen should that not be the case.
