### ISSUE TITLE
mysql logs are too hard to understand 

### ISSUE THREAD

**Issue by krsu** [J-Tanzanite/Little-Anti-Cheat#175]
will there be any updates soon to make the mysql version of the logs easier to understand? 

the SQLite version was easy to comprehend, but i wanted all of the servers to merge logs to a single location so its easier to go through them ;w;

I love the plugin and keep up the good work!

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies, if you have any specific requests for changes to SQL logging, feel free to reopen or comment below :)
