### ISSUE TITLE
[FoF] Possible false-positives for "Angle-Cheats" in game Fistful of Frags

### ISSUE THREAD

**Issue by Mecha-Weasel** [J-Tanzanite/Little-Anti-Cheat#177]
When I first started using Lilac on my [Fistful of Frags](https://store.steampowered.com/app/265630/Fistful_of_Frags/) (FoF) servers, I started almost immediately getting a bunch of "Angle-Cheat" detections - including from regular players I am confident were not cheating.

I treated this is a false-positive, disabled Angle-Cheat detection and un-banned everyone banned for that reason on those servers.

Perhaps the thresholds for Angles/views is different in [Fistful of Frags](https://store.steampowered.com/app/265630/Fistful_of_Frags/)?

**Comment by J-Tanzanite** [comment]
Yeah FOF isn't tested with Lilac, what were the angles in the logs? (Please don't share IPs or SteamIDs, just the angles)

**Comment by J-Tanzanite** [comment]
Hey, any update on the logs?

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies, feel free to reopen with logs or further questions if any :)

**Comment by Mecha-Weasel** [comment]
Sorry, where i what logs? I may not have preserved that data.

**Comment by J-Tanzanite** [comment]
The log should be here on the server: `addons/sourcemod/logs/lilac.log`

**Comment by Mecha-Weasel** [comment]
Thanks for the info, and the follow-up.
Unfortunately, I have some log-clean-up processes that zip up stuff in the folder, and since the file does not incorporate a date-code in its name, it keeps getting overwritten in the backups - loosing any previous version with useful information it it.
I'll have to adapt my clean-up process to exclude lilac.log, to not interfere with preservation of the events.
I will do so, and wait for it to happen again.

**Comment by Mecha-Weasel** [comment]
Got a new detection for angle-cheats last night:

```
2023/07/20 18:11:16 [Version 1.7.4] {Name: "Orbus" | SteamID: STEAM_0:0:xxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.02, Yaw: -87.65, Roll: 0.00).
	Pos={5131,5827,448}, Angles={89.02366,-87.65612,0.00000}, Map="fof_depot_2014a", Team={3}, Weapon="weapon_spencer", Latency={Inc:0.010751,Out:0.064349}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.567933,Out:0.010598}, ConnectionTime={812.145507 seconds}, GameTime={1116.479980 seconds}
```

NOTE: Player's actual info (SteamID & IP Address) have been redacted for their privacy.

**Comment by Mecha-Weasel** [comment]
### More sample Angle-Cheat detections:
NOTE: Player's actual info (Name, SteamID & IP Address) have been redacted for their privacy.

2023/07/20 18:11:16 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:0:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.02, Yaw: -87.65, Roll: 0.00).
	Pos={5131,5827,448}, Angles={89.02366,-87.65612,0.00000}, Map="fof_depot_2014a", Team={3}, Weapon="weapon_spencer", Latency={Inc:0.010751,Out:0.064349}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.567933,Out:0.010598}, ConnectionTime={812.145507 seconds}, GameTime={1116.479980 seconds}

2023/07/20 20:44:49 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.01, Yaw: 178.65, Roll: 0.00).
	Pos={5164,6069,438}, Angles={89.01334,178.65994,0.00000}, Map="fof_depot_2014a", Team={2}, Weapon="weapon_remington_army2", Latency={Inc:0.010641,Out:0.101012}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.551899,Out:0.340839}, ConnectionTime={2371.594726 seconds}, GameTime={352.514984 seconds}

2023/07/20 21:37:15 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:0:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.01, Yaw: -88.12, Roll: 0.00).
	Pos={1027,1000,408}, Angles={89.01080,-88.12443,0.00000}, Map="fof_revenge_2014a", Team={5}, Weapon="weapon_remington_army2", Latency={Inc:0.011039,Out:0.178400}, Loss={Inc:0.027492,Out:0.000000}, Choke={Inc:0.538473,Out:0.275710}, ConnectionTime={1952.395141 seconds}, GameTime={1003.739990 seconds}

2023/07/20 22:18:42 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.02, Yaw: 48.36, Roll: 0.00).
	Pos={810,331,144}, Angles={89.02162,48.36051,0.00000}, Map="fof_loothill_v39a", Team={4}, Weapon="weapon_carbine", Latency={Inc:0.004045,Out:0.218291}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.044257,Out:0.571292}, ConnectionTime={466.500885 seconds}, GameTime={996.434997 seconds}

2023/07/21 01:32:55 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.01, Yaw: -39.32, Roll: 0.00).
	Pos={1440,1999,586}, Angles={89.01249,-39.32703,0.00000}, Map="fof_revenge_2014a", Team={3}, Weapon="weapon_fists", Latency={Inc:0.010148,Out:0.113435}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.558502,Out:0.045952}, ConnectionTime={2831.694824 seconds}, GameTime={173.804992 seconds}

2023/07/21 20:23:56 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:0:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.01, Yaw: 159.77, Roll: 0.00).
	Pos={4536,4112,0}, Angles={89.01856,159.77951,0.00000}, Map="fof_sawmill_b6", Team={4}, Weapon="weapon_bow", Latency={Inc:0.001490,Out:0.078601}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.101605,Out:0.510498}, ConnectionTime={183.527618 seconds}, GameTime={607.320007 seconds}

2023/07/21 21:06:08 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.02, Yaw: -147.44, Roll: 0.00).
	Pos={5282,4121,239}, Angles={89.02311,-147.44888,0.00000}, Map="fof_depot_2014a", Team={4}, Weapon="weapon_bow", Latency={Inc:0.009140,Out:0.082065}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.556834,Out:0.145338}, ConnectionTime={2944.923095 seconds}, GameTime={644.940002 seconds}

2023/07/22 00:00:38 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.01, Yaw: 162.51, Roll: 0.00).
	Pos={4456,4159,0}, Angles={89.01507,162.51759,0.00000}, Map="fof_sawmill_b6", Team={3}, Weapon="weapon_shotgun", Latency={Inc:0.009464,Out:0.069790}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.557533,Out:0.017272}, ConnectionTime={1127.099609 seconds}, GameTime={1135.380004 seconds}

2023/07/22 00:07:42 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.02, Yaw: 109.78, Roll: 0.00).
	Pos={-284,-48,144}, Angles={89.02036,109.78552,0.00000}, Map="fof_loothill_v39a", Team={4}, Weapon="weapon_shotgun", Latency={Inc:0.011081,Out:0.113259}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.556034,Out:0.011969}, ConnectionTime={2121.586914 seconds}, GameTime={312.119995 seconds}

2023/07/22 00:21:38 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: 89.02, Yaw: 73.37, Roll: 0.00).
	Pos={528,1391,128}, Angles={89.02761,73.37464,0.00000}, Map="fof_loothill_v39a", Team={5}, Weapon="weapon_fists", Latency={Inc:0.000778,Out:0.072577}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.011302,Out:0.622648}, ConnectionTime={796.981811 seconds}, GameTime={1147.859985 seconds}

2023/07/22 00:54:12 [Version 1.7.4] {Name: "REDACTED" | SteamID: STEAM_0:1:xxxxxxxxx | IP: xxx.xxx.xxx.xxx} was detected and banned for Angle-Cheats (Pitch: -89.01, Yaw: -146.19, Roll: 0.00).
	Pos={-263,-296,-583}, Angles={-89.01064,-146.19230,0.00000}, Map="fof_cripplecreek_v39c", Team={3}, Weapon="weapon_sawedoff_shotgun2", Latency={Inc:0.012982,Out:0.116754}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.551728,Out:0.220059}, ConnectionTime={568.095397 seconds}, GameTime={606.239990 seconds}
