### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by nereyegeldikabi** [J-Tanzanite/Little-Anti-Cheat#179]
i just installed this plugin but it keeps banning myself from my server without any cheats..

**Comment by azalty** [comment]
Game?

You're a cheater :)

**Comment by nereyegeldikabi** [comment]
bro i have installed it on my own server + i have 27k hours ingame never used cheats so far..
not sure why banned me when i had z root also the reason was sv_cheats 1 cvar change, disabled the cvar detect from 1 to 0 and now is not banning me ..

**Comment by nereyegeldikabi** [comment]
thanks for the answer, also what's the correct detection percent? 

[Lilac] WHATLAN is suspected of using 'Aimbot' 

i have received that message exactly 5 times and the player got banned from my server after 5 warns, but the player is telling me he was not using any cheats + he had some expensive skins on his inventory

**Comment by azalty** [comment]
do you have demo/gotv/recordings?

You should also be able to check the detection logs in sourcemod/logs/ - paste those here, and remove their IP

**Comment by J-Tanzanite** [comment]
Closing this due to lack of replies, feel free to reopen with logs or further questions :)
