### ISSUE TITLE
IP ban doesn't seem to work

### ISSUE THREAD

**Issue by mrdiega** [J-Tanzanite/Little-Anti-Cheat#183]
material admin config.cfg:
```
// Type server ban. 
// 1 - SteamID. 
// 0 - IP.
"ServerBanTyp" "0"
```
lilac_config.cfg:
```
lilac_materialadmin "1"
```

However, bans are still issued on SteamID

074 "Material Admin" (0.8.6-ae3f5b9)
125 "[Lilac] Little Anti-Cheat" (1.7.4)

**Comment by azalty** [comment]
https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/scripting/lilac/lilac_stock.sp#L283

LilAC forces SteamID bans here ^

**Comment by mrdiega** [comment]
> https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/scripting/lilac/lilac_stock.sp#L283
> 
> LilAC forces SteamID bans here ^
i changed to:
```MABanPlayer(0, client, MA_BAN_IP, get_ban_length(cheat), reason);```
But I get an error when compiling::
```// lilac\lilac_stock.sp(283) : error 017: undefined symbol "MA_BAN_IP" ```

**Comment by azalty** [comment]
> ```// lilac\lilac_stock.sp(283) : error 017: undefined symbol "MA_BAN_IP" ```

Write 2 and it should work
