### ISSUE TITLE
[FoF] Possible false-positives for "No-Lerp" in game Fistful of Frags

### ISSUE THREAD

**Issue by Mecha-Weasel** [J-Tanzanite/Little-Anti-Cheat#185]
I have noticed a few no-lerp detections in Fistful of Frags (FoF).

What makes me think that they are false-positives (besides players claiming they don't even know what that is), is the way the bans are showing-up (in particular in SourceBans++).

Checking the **addons/sourcemod/logs/lilac.log** file, I see matching information like this:

```
2023/07/20 00:33:09 [Version 1.7.4] {Name: "C3PO [bot]" | SteamID: STEAM_0:0:xxxxxxxx | IP:xxx.xxx.xxx.xxx} was detected and banned for NoLerp (0.000000ms).
	Pos={688,800,-139}, Angles={-0.42187,89.57812,0.00000}, Map="fof_robertlee_2014a", Team={2}, Weapon="weapon_fists", Latency={Inc:-1.000000,Out:-1.000000}, Loss={Inc:-1.000000,Out:-1.000000}, Choke={Inc:-1.000000,Out:-1.000000}, ConnectionTime={0.000000 seconds}, GameTime={12.989999 seconds}
```
Very suspect is that in the log and the ban, it does not have the correct name for that player matching what is on their Steam profile.  Instead it has the name of **_one of the bots_** on the server.

Each time I have seen this ban (3 or 4 times so far), it is always the same way - as if it is confusing a bot with an actual player.

NOTE: Player's _actual_ info (SteamID &  IP Address) have been redacted for their privacy.

**Comment by sapphonie** [comment]
Hmmm, this smells like an issue with SourceMod offsets/gamedata being wrong...
Can you try writing a plugin that uses `%N` and `%L` with a client index, and report back if you notice any strange behavior? I can't see anywhere in the code where this could happen

**Comment by sapphonie** [comment]
Please recheck this on the latest versions of SourceMod and Metamod. Until then, closing
