### ISSUE TITLE
[Discussion] Relationship between Spectator Perspective and Cheaters (L4D2)

### ISSUE THREAD

**Issue by PencilMario** [J-Tanzanite/Little-Anti-Cheat#188]
Recently, my friends tested and found that if someone uses 'no recoil' and 'no spread' cheats, when spectators observe this player, the player's perspective appears lower than normal, as if they were crouching.

However, as far as I know, if the spectator perspective is too low, it can also be resolved by recording a demo. I tend to think this might be a client-side bug. Does anyone have any insights?

_I used ChatGPT for translation because my English is average. :)_

**Comment by SirPlease** [comment]
This is not an indicator of cheats, this is just a client side bug that can occur on any player that you're spectating.
If only it were that easy to know if someone was cheating though 😄
