### ISSUE TITLE
lilac_set_ban_length does not register to lilac.config

### ISSUE THREAD

**Issue by Neigeflocon** [J-Tanzanite/Little-Anti-Cheat#193]
Hi, the plugin rewrites when I try to add lilac_set_ban_length bhop 5 to the config file itself, writing it on the rcon works however is there a way to make this permanent?

**Comment by azalty** [comment]
You must not add anything to the plugin's auto-generated .cfg file located in `gameFolder/cfg/`

Writing `sm_rcon lilac_set_ban_length bhop 5` in `/cfg/server.cfg` should do the trick. If you're running csgo on the casual gamemode, you could also try writing this in `/cfg/gamemode_casual_server.cfg`

I sadly didn't take this into account when changing the auto config system to a better one, which caused this issue to appear.\
I didn't think about this use case, so I hope server.cfg will work.

**Comment by Neigeflocon** [comment]
Thank you, I'll put the length codes there. Another question I have is that is there a way to customize ban messages for specific reasons?

For example I wish to make bhop ban for 5 minutes, and it should ideally write "bhop is not allowed, please take 5 minutes to remove it." or something.

**Comment by azalty** [comment]
You could modify [this line](https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/scripting/lilac/lilac_stock.sp#L260) to remove the Lilac tag, or just [modify this translation phrase](https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/translations/lilac.phrases.txt#L53)

You seem to have a french username. If your server's lang is set to FR, you should modify this [translation file instead](https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/translations/fr/lilac.phrases.txt#L48)

**Comment by Neigeflocon** [comment]
Thank you
