### ISSUE TITLE
add text filter

### ISSUE THREAD

**Issue by panikajo** [J-Tanzanite/Little-Anti-Cheat#28]
hi, can u add text filter?
for this bug
![20200720222415_1](https://user-images.githubusercontent.com/4964185/87985127-c2095580-cae3-11ea-953c-08d8de1c471a.jpg)

**Comment by J-Tanzanite** [comment]
Chat and name filters is something I've thought about adding in later versions.
I think the text you're seeing there is in 3kliksphilips video about "longest killfeed", and that character is obscenely long.

When I get around to adding a chat filter, I'll blacklist that character, for sure. :)
Perhaps I should start working on this in version 1.7.0, as a beta feature...

**Comment by J-Tanzanite** [comment]
I don't really have any other way of contacting you, so I'll just put this here.

The changelog/updates listed on hlmod.ru are incomplete and missing a lot of stuff. Some of which are important!

You can find all the correct changes here: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/Changelog
Please update hlmod.ru with the correct information :)
