### ISSUE TITLE
Add Github Sponsors / Patreon

### ISSUE THREAD

**Issue by estiawan** [J-Tanzanite/Little-Anti-Cheat#36]
Add Github Sponsors / Patreon for Support Little Anti Cheat

**Comment by J-Tanzanite** [comment]
I'll look into it :)

**Comment by J-Tanzanite** [comment]
Sorry for the late reply, but I've decided to stick with steam item donations only.
It's simpler, much more convenient and more accessible considering Lilac is for games.

That said, Little Anti-Cheat will remain free forever, donations are voluntary and optional.
If you can't or don't wanna donate through steam - that's perfectly fine :)
