### ISSUE TITLE
[Request] Add ban length ConVar

### ISSUE THREAD

**Issue by panikajo** [J-Tanzanite/Little-Anti-Cheat#4]
Hello, can u add please time ban cvar?

**Comment by J-Tanzanite** [comment]
Sure, I'll add a convar for ban length.

**Comment by J-Tanzanite** [comment]
Going to consider this issue closed and solved, but going to leave this up for a few days, in case there is a bug. :)

**Comment by panikajo** [comment]
> Going to consider this issue closed and solved, but going to leave this up for a few days, in case there is a bug. :)
hm, have problem new version don't create cfg.

**Comment by J-Tanzanite** [comment]
You need to delete the old config for the new config to generate, or else it will just use the old config.

Basically: Delete **cfg/lilac_config.cfg**
And then restart the server.
The new config will be generated here **cfg/sourcemod/lilac_config.cfg**

**Comment by panikajo** [comment]
> You need to delete the old config for the new config to generate, or else it will just use the old config.
> 
> Basically: Delete **cfg/lilac_config.cfg**
> And then restart the server.
> The new config will be generated here **cfg/sourcemod/lilac_config.cfg**

and where are the logs created? I looked everywhere but did not find them.

**Comment by J-Tanzanite** [comment]
Because a lot of people have requested that I move it, I recently did in version 1.3.0 -> 1.4.0.

Detection logs moved from **csgo/lilac.log** to **addons/sourcemod/logs/lilac.log**.

**Comment by panikajo** [comment]
> Because a lot of people have requested that I move it, I recently did in version 1.3.0 -> 1.4.0.
> 
> Detection logs moved from **csgo/lilac.log** to **addons/sourcemod/logs/lilac.log**.
i use last build, and today the player for aim was banned but there are no logs

**Comment by panikajo** [comment]
> Because a lot of people have requested that I move it, I recently did in version 1.3.0 -> 1.4.0.
> 
> Detection logs moved from **csgo/lilac.log** to **addons/sourcemod/logs/lilac.log**.

**Comment by panikajo** [comment]
Can you add some cvars?
aim -> lilac_bantime_aim 
bhop -> lilac_bantime_bhop

**Comment by J-Tanzanite** [comment]
I feel like adding several convars for ban lengths may be a little overkill.
Though I can see the argument for it, it just seems way too much.

I'll consider it.

**Comment by J-Tanzanite** [comment]
Alright, I've thought about this a lot now, and I've decided not to add more ConVars for controlling ban length.

Most server owners would prefer to only have one, it makes things simple, doesn't make a mess of the config file and most people will want perma bans anyway...

That said, I did decide to fulfill your request, so now there is a new command that lets you control the ban length of specific cheat features: **lilac_set_ban_length**

You can use it like so: **lilac_set_ban_length bhop 15**
Which sets bhop ban length to 15 minutes.
If you want to disable the overwrite and use "lilac_ban_length" instead,
just do **lilac_set_ban_length bhop -1**

You can find the latest development stuff here:
https://github.com/J-Tanzanite/Little-Anti-Cheat/tree/development
Keep in mind, the development branch is **NOT STABLE.**
It is called "development" for a reason. Once version 1.5.0 is finished and stable, it will be moved to the master branch.
