### ISSUE TITLE
[QUESTION] about bunny hop

### ISSUE THREAD

**Issue by penalte** [J-Tanzanite/Little-Anti-Cheat#44]
Hello, thank you for this plugin it has helped me alot.

My question is if there is natives that i can use to recode my store bunny hop plugin so it only check the player if he does not have bunny hop equiped in the store.

THANK YOU FOR THIS AMAZING ANTI CHEAT.

Regards.

**Comment by J-Tanzanite** [comment]
Thank you :)

There are no natives that lets you tell Lilac not to test a player for something.
But, Lilac does provide a Forward you can use to block cheat detections. :)

``` c
// This define is from lilac.sp, and won't ever change.
#define LILAC_CHEAT_BHOP 4

public Action lilac_allow_cheat_detection(int client, int cheat)
{
	// player_has_bhop(int client) doesn't actually exist,
	// 	you have to add your own test to see if a player has bought bhop.
	if (cheat == LILAC_CHEAT_BHOP && player_has_bhop(client))
		return Plugin_Stop; // Stop the detection, as this player has bought Bhop from store.

	// Allow the detection to go through.
	return Plugin_Continue;
}
```

Add this forward to your code, and you can then block Bhop detections for players who have bought it from your store.

**Comment by J-Tanzanite** [comment]
Did it work for you?

**Comment by J-Tanzanite** [comment]
It's been a few days and I haven't heard any further from you.
Considering blocking this Forward has worked for others, I am going to assume this has worked for you too.

I'm going to close this issue, if you have any problems with blocking Bhop detections or such, feel free to reopen this issue :)
