### ISSUE TITLE
Ignores the cheater.

### ISSUE THREAD

**Issue by Dancbeunny98** [J-Tanzanite/Little-Anti-Cheat#46]
Any paid cheat is ignored by the anti-cheat. The man spins and runs quietly, jumps, shoots through walls and so on. The only function that works flawlessly is the fast squat.

There is no information in the log files.
The latest version of the anti-cheat is used and no changes have been made.

UDP: I apologize in advance that there was no response to previous inquiries. In fact, I could not answer them as there was little information and they are very stupid.

**Comment by J-Tanzanite** [comment]
I've already answered you previously, stating that I **cannot** help you (Source: https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/45#issuecomment-712161550).

I'll repeat myself here: **"You need to talk to a Russian developer".**
For me to help you, we need to speak the same language, we and we don't.

You also provide little to no information for me to work with. So again:
**"You need to talk to a Russian developer".**

---

Look, I'm not saying this to be rude, but you have to understand.
You seem to have problems no one else seems to have, in addition to this, based on your pull request and comments so far, you don't seem to know what you are doing.
And you struggle to point out what your problems are, with details that would be needed for me to help.
In order for me to help guide you through this, and understand exactly what your problems are - we would **have** to speak the same language, and we don't.
You need someone who understands Russian and speaks Russian who can help you.

Sorry, but I cannot help you.
