### ISSUE TITLE
[Request] Auto Updater

### ISSUE THREAD

**Issue by J-Tanzanite** [J-Tanzanite/Little-Anti-Cheat#5]
Could you make use of the updater plugin so this auto updates so dont have to check git repo :S

_Originally posted by @TonyS95 in https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/3#issuecomment-623204854_

**Comment by J-Tanzanite** [comment]
I haven't looked into auto updating plugins yet, but I will soon.
Currently, I'm a little busy with a few other things, so it might take a while, but it is coming.
No idea when it will be added tho

**Comment by J-Tanzanite** [comment]
Version 1.6.0-RC 1 (In development branch https://github.com/J-Tanzanite/Little-Anti-Cheat/tree/development) now has auto-updating.
It's still in beta, but should work :)

**Comment by borzaka** [comment]
I have issues with the auto update feature;
```
L 06/21/2020 - 11:37:30: [SM] Exception reported: Native is not bound
L 06/21/2020 - 11:37:30: [SM] Blaming: lilac.smx
L 06/21/2020 - 11:37:30: [SM] Call stack trace:
L 06/21/2020 - 11:37:30: [SM]   [0] Updater_AddPlugin
L 06/21/2020 - 11:37:30: [SM]   [1] Line 711, lilac.sp::lilac_update_url
L 06/21/2020 - 11:37:30: [SM]   [2] Line 675, lilac.sp::cvar_change
```
Version 1.6.0-RC 1

I had to disable `lilac_auto_update` to make the errors go away.

Maybe I should install the Updater plugin? :D
https://forums.alliedmods.net/showthread.php?p=1570806
Silly me... Worth a note in the readme...

**Comment by J-Tanzanite** [comment]
Yeah, I should have written it in the readme.md... Oops

And yeah, maybe I should add a check to actually mare sure the updater is present before using it :'D

A while ago you mentioned I should use SMAC's method of checking if a native is present.
And I think that's a good idea!

`GetFeatureStatus()` can be used to check if the function `Updater_AddPlugin()` is present... I'll add this to the Release Candidate 3 :)

**Comment by borzaka** [comment]
I don't think that you should allow users to change the update URL. That's a huge security risk, and users can break this functionality completely. I would define the update url only in the source code:
`#define UPDATE_URL "https://raw.githubusercontent.com/J-Tanzanite/Little-Anti-Cheat/development/updatefile.txt"`
I think this is the best practice.

And you can check like this:
```
#if defined _updater_included
if (LibraryExists("updater"))
{
	Updater_AddPlugin(UPDATE_URL);
}
#endif

#if defined _updater_included
public Updater_OnPluginUpdated()
{
	ReloadPlugin(INVALID_HANDLE);
}
#endif

public OnLibraryAdded(const String:name[])
{
	#if defined _updater_included
	if (StrEqual(name, "updater"))
	{
		Updater_AddPlugin(UPDATE_URL);
	}
	#endif
}
```
Code taken from: https://forums.alliedmods.net/showthread.php?p=2636300

**Comment by J-Tanzanite** [comment]
I want server owners to be able to set their own URL with ease, and not having to update the source code.

I wasn't sure what you mean by "That's a huge security risk"...
I know people can insert invalid URLs, but that's fine... People can screw up the URL all they want, it isn't going to break the AC.

Since you didn't tell me where the security issue lies (just that there is one, but no information about it), I took a break to think about it.
And I think you are referring to the command "sm_rcon", which could be used to change the URL to anything malicious... However, if you already have access to sm_rcon, then you pretty much already have everything you need to screw up the server.
Fact of the matter is, sm_rcon shouldn't be trusted to everyone.

...
That said, I don't think you can delete/modify files via sm_rcon...
But if you can install any plugin you want to the server, then you might be able to...
It could potentially grant you further access than what sm_rcon allows, just by changing a single ConVar.

I think this is what you are referring to.
In which case, sure, I'll revert back to Dev 1, when it was hardcoded.
Nice catch!

**Comment by borzaka** [comment]
Why would you let users change the update URL of your plugin? This repo is the official one, and you are controlling your own updates.
I just wanted to point out that that was not the best practice. I haven't seen any plugin used updater to let people change it. No need to, only if you move the sourcecode to somewhere else.

**Comment by J-Tanzanite** [comment]
The original idea was that server owners could easily fork my project, and in their cfg/sourcemod/lilac_config.cfg file, set the update link to their own fork.
That way, server owners who had lots of servers could automatically update all of their servers with the version of Lilac that they trust.

---

Lets say that you had 30 servers, and you want to be able to update all of them with a single version of Lilac.
But, you don't trust my updates, you wanna test out each update before applying it to all of your servers.

As an example, lets say you are using version 1.6.0 in all your servers, and I've released version 1.7.0.
You would like to have the convenience of updating all of your servers at once, but you don't trust version 1.7.0.
So, you've set your servers to download from your own fork.
You could test out version 1.7.0 in a local server or on a test server, and once you've tested it out and you trust that version 1.7.0 is safe, doesn't have any bugs and doesn't contain any malicious code, you can then pull from me to your own fork.
All your servers will then later see that your own fork has an update (which you trust) and they will then download and use that.

---

Using a ConVar means that even if you pull directly from me, the CFG file will still have the link to your own fork and not mine, which means that you don't have to change the URL in the sourcecode before pulling from me.
It just makes it more convenient.

---

And yeah, when it comes to not trusting this official repo...
There are server owners who don't trust me.
I'm unsure how much you know about me, but I used to cheat a lot in TF2 back in 2015-2018, and people would really hate me.
Because of this, to this day a lot of people don't trust me, and that's fair.

If you do trust me, that's nice ^-^
But it's not the most secure thing you can do.

You shouldn't trust random people online with direct access to your servers.
Even if it is open source and you can see the changes I make, it may be too late if I suddenly go rouge (which I won't) or my account gets hacked.
It is far safer to use your own fork of Lilac and set your servers to update from that.

---

That's the reasoning behind the ConVar controlling the URL.
But as previously discussed, sm_rcon might cause this to be a security flaw, so it is now hardcoded in version 1.6.0-RC 4 (Which is out now, and you should use that version).

In terms of using your own fork for security reasons...
I guess you could fork directly from me into a different branch, change the URL in the sourcecode and then merge from that branch into your master branch...
That should be fairly easy to do.

**Comment by borzaka** [comment]
Hmm, I would skip that fuss forking and compiling with a custom update URL every time you release an update. But I understand your point.
Instead I would disable the auto update feature, and keep an eye of your updates and update manually, and revert back if something is broken. I like to know what changed.

**Comment by J-Tanzanite** [comment]
I see.

Oh, btw, does auto update actually work now?
It's not something I've tested, does it work for you?

**Comment by borzaka** [comment]
I just updated manually to 1.6.0-RC 4, and enabled update. So, see you at the next update! :D

**Comment by J-Tanzanite** [comment]
Sorry for the terribly late update, I've been moving as of late and haven't had much time or internet to work on Lilac. I am back now (sorta) and with a new update; Version 1.6.0-RC 5.

Hopefully the auto-updater works as intended, and sourcebans++ & material-admin support should work much better now.
There are some new ConVars, so you might have to reset the config file after the new version is installed.

I will not add more features now, and I will solely focus on bug fixes if any issues arise. I want version 1.6.0 to get released officially :P... As it's been a long time since my last official update.

Looking forward hearing back from you on how this update works~

**Comment by borzaka** [comment]
The update failed:
```
L 07/11/2020 - 22:11:48: SMC parsing error on line 10
L 07/11/2020 - 22:11:48:   [0]  URL: https://raw.githubusercontent.com/J-Tanzanite/Little-Anti-Cheat/development/updatefile.txt
L 07/11/2020 - 22:11:48:   [1]  ERROR: Line contained too many invalid tokens
```

But regarding this post, it was probably a temporary GitHub down issue:
https://forums.alliedmods.net/showpost.php?p=2418030&postcount=563

I tried to run it manually with `sm_updater_check`, but nothing happened:
```
sm_updater_check
[Updater] Checking for updates.
```

**Comment by J-Tanzanite** [comment]
That's kinda weird... I do have a new version tho, version 1.6.1-RC 5.
I found some tiny things I had forgotten, and some tiny stuff that could be adjusted.

Releasing that version now with those fixes, hopefully the updater works this time.
If it doesn't, then I don't think the issue lies with the updater.

**Comment by borzaka** [comment]
I will wait, maybe the next update check will be successful. I will report back!

**Comment by borzaka** [comment]
Well, still no update, but I see the error now. Unfortunately it's in the `updatefile.txt` as the error message says.
You shouldn't include more `"` inside `""`s

So, these lines has errors:
`"Notes" "Added new backtrack patch method, "Lock". This patch method shouldn't affect laggy legit players much."`
`"Notes" "Added new ConVar "lilac_max_ping_spec" (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds."`

Replace the inner `""` to `''`:
`"Notes" "Added new backtrack patch method, 'Lock'. This patch method shouldn't affect laggy legit players much."`
`"Notes" "Added new ConVar 'lilac_max_ping_spec' (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds."`

And check other syntax errors.

**Comment by J-Tanzanite** [comment]
Ohh I... Umm... I... ehh... Umm...
...
I have a very large brain x'D

How did I **NOT** notice that?!
Now THAT'S a big brain moment right there. I'll fix it rn, sorry.
... :'D

**Comment by J-Tanzanite** [comment]
I fixed all the issues I could find, so the auto-update should work.
If all is well, this version will become the official release.

**Comment by borzaka** [comment]
Well, the updater is not updated ever since :( I had server restarts, but nothing. Maybe SteamWorks (the recommended for Updater) is causing it, I have updated it as well.

```
sm_updater_status
[Updater] -- Status Begin --
Plugins being monitored for updates:
  [0]  updater.smx
  [1]  afk_manager4.smx
  [2]  smacbans-block.smx
  [3]  lilac.smx
Last update check was 10.7 minutes ago.
[Updater] --- Status End ---
```
But it's still:
`"[Lilac] Little Anti-Cheat" (1.6.0-RC 4) by J_Tanzanite`

I don't know what I'am is missing.

**Comment by J-Tanzanite** [comment]
I removed the newlines, try now...
If it still doesn't work, then I suspect it's the updater itself... Maybe... Which wouldn't make much sense either.

**Comment by J-Tanzanite** [comment]
Small update, because you were having issues with this, I tried to do it myself.
I setup a test server, and this is my result: 
``` text
[SM] The plugin list has been refreshed and reloaded.
L 07/15/2020 - 19:29:46: SMC parsing error on line 0
L 07/15/2020 - 19:29:46:   [0]  URL: http://godtony.mooo.com/updater/updater.txt
L 07/15/2020 - 19:29:46:   [1]  ERROR: Line contained too many invalid tokens
L 07/15/2020 - 19:29:47: Update available for "[Lilac] Little Anti-Cheat" (lilac.smx). Current: 1.6.0-RC 4 - Latest: 1.6.1-RC 5
L 07/15/2020 - 19:29:47:   [0]  Added new BETA (May not work) TF2 cheat detection for Infinite Noisemaker Spam. Since it is in BETA, it WON'T ban, only log! If no false positives are reported, it will perma ban in the future.
L 07/15/2020 - 19:29:47:   [1]  Added new backtrack patch method, 'Lock'. This patch method shouldn't affect laggy legit players much.
L 07/15/2020 - 19:29:47:   [2]  Added new ConVar 'lilac_max_ping_spec' (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds.
L 07/15/2020 - 19:29:47:   [3]  Added a delay for forwards so they won't get spammed to other plugins.
L 07/15/2020 - 19:29:47:   [4]  Updated how banning works through Sourcebans++/MaterialAdmin, it will now check if the native exists and not if the plugin by name is loaded.
L 07/15/2020 - 19:29:47:   [5]  Updated ConVar checker to be more basic and less CPU intensive.
L 07/15/2020 - 19:29:47:   [6]  Removed Anti-Duck-Delay/FastDuck's 1 week back length, it now perma bans.
L 07/15/2020 - 19:29:47:   [7]  Version 1.6.1-RC 5 Fixes:
L 07/15/2020 - 19:29:47:   [8]  Added noisemaker to lilac_set_ban_length command... Ops, forgot about that.
L 07/15/2020 - 19:29:47:   [9]  Updated general mistakes here and there.
L 07/15/2020 - 19:29:51: Successfully updated and installed "[Lilac] Little Anti-Cheat".
sm plugins list
[SM] Listing 20 plugins:
  01 "[Lilac] Little Anti-Cheat" (1.6.0-RC 4) by J_Tanzanite
...
  06 "Updater" (1.2.2) by GoD-Tony
sm plugins refresh
[Little Anti-Cheat 1.6.1-RC 5] Successfully loaded!
[SM] The plugin list has been refreshed and reloaded.
=========[Lilac Ban Status]=========
Checking ban plugins:
Material-Admin:
        Loaded: No
        Native Exists: No
        ConVar: lilac_materialadmin = 0
Sourcebans++:
        Loaded: No
        Native Exists: No
        ConVar: lilac_sourcebans = 0

Banning will go though BaseBans.
```

As you can see, it did download it, but it never refreshed the plugin.
After I did so manually, it worked.

If it isn't working for you, then I suspect it really is just the updater plugin messing up somehow.

**Comment by borzaka** [comment]
I don't understand why isn't working. Are you using SteamWorks?

**Comment by J-Tanzanite** [comment]
Yes, however, I did recompile the binary myself.

You see, when I installed the updater plugin, it told me I had to wait an hour before being allowed to check for updates...
So I did the only sensible thing when all I wanted to do was test it, and I recompiled it without the 1 hour check.

That's all I changed.
I was using updater version 1.2.2, and I am assuming you're using the same version, so that can't be the issue.
What version of SteamWorks are you using?

**Comment by borzaka** [comment]
First, I used the latest from here: http://users.alliedmods.net/~kyles/builds/SteamWorks/
But later I updated to this version here: https://github.com/KyleSanderson/SteamWorks/releases

I'am using the already compiled version downloaded from the original thread: https://forums.alliedmods.net/showthread.php?p=1570806

I now tried to compile myself, but multiple errors regarding SteamWorks, even with the updated syntax downloaded from here:
https://forums.alliedmods.net/showpost.php?p=2709444&postcount=632
(I don't trust the compiled version included that zip.)
```
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(215) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(216) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(217) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(218) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(219) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(219) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(220) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(220) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(221) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(221) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(222) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(223) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(223) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(223) : error 147: new-style declarations are required
/csgo/addons/sourcemod/scripting/include/SteamWorks.inc(223) : fatal error 190: too many error messages on one line
```

**Comment by J-Tanzanite** [comment]
Due to the old syntax, I downloaded Sourcemod version 1.7 to my desktop, and compiled the binary there, and then put that compiled binary onto my server (which is running Sourcemod version 1.10).
And that worked for me...

**Comment by borzaka** [comment]
Well, I'am gonna stick to the manual update then... :D

**Comment by J-Tanzanite** [comment]
OOF.
Well, I guess that's pretty much the only option left, something about the updater is acting weird, and we're not able to figure out what.

Anyway, since I managed to get auto-updater to work on my end but you didn't, I'm going to consider this issue half-solved.
I'll leave this issue open in case others have problems or new information.

This is the last release candidate, and if no issues are reported on it within 2-5 days, it will get released as the official new version. c:

**Comment by borzaka** [comment]
Hmm, yes, the Updater is acting weird. Today I have received the updates. But in a strange form. The Updater thinks that every update is an Updater update :)

Currently this is my update enabled plugins:
```
[0]  updater.smx (1.2.2)
[1]  afk_manager4.smx (4.3.0)
[2]  smacbans-block.smx (0.2.0)
[3]  lilac.smx (1.6.0-RC 4)
```

Check this logs:
```
L 07/18/2020 - 06:43:02: Update available for "Updater" (updater.smx). Current: 1.2.2 - Latest: 0.2.0
L 07/18/2020 - 06:43:06: Successfully updated and installed "Updater".
L 07/18/2020 - 06:43:06: Reloading Updater plugin... updates will resume automatically.
L 07/18/2020 - 06:43:07: Update available for "Updater" (updater.smx). Current: 1.2.2 - Latest: 4.3.0
L 07/18/2020 - 06:43:07:   [0]  More info @ http://forums.alliedmods.net/showthread.php?t=79904
L 07/18/2020 - 06:43:07:   [1]  Check the forums for change notes...
L 07/18/2020 - 06:43:07: Update available for "[Lilac] Little Anti-Cheat" (lilac.smx). Current: 1.6.0-RC 4 - Latest: 1.6.1-RC 5
L 07/18/2020 - 06:43:07:   [0]  Added new BETA (May not work) TF2 cheat detection for Infinite Noisemaker Spam. Since it is in BETA, it WON'T ban, only log! If no false positives are reported, it will perma ban in the future.
L 07/18/2020 - 06:43:07:   [1]  Added new backtrack patch method, 'Lock'. This patch method shouldn't affect laggy legit players much.
L 07/18/2020 - 06:43:07:   [2]  Added new ConVar 'lilac_max_ping_spec' (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds.
L 07/18/2020 - 06:43:07:   [3]  Added a delay for forwards so they won't get spammed to other plugins.
L 07/18/2020 - 06:43:07:   [4]  Updated how banning works through Sourcebans++/MaterialAdmin, it will now check if the native exists and not if the plugin by name is loaded.
L 07/18/2020 - 06:43:07:   [5]  Updated ConVar checker to be more basic and less CPU intensive.
L 07/18/2020 - 06:43:07:   [6]  Removed Anti-Duck-Delay/FastDuck's 1 week back length, it now perma bans.
L 07/18/2020 - 06:43:07:   [7]  Version 1.6.1-RC 5 Fixes:
L 07/18/2020 - 06:43:07:   [8]  Added noisemaker to lilac_set_ban_length command... Ops, forgot about that.
L 07/18/2020 - 06:43:07:   [9]  Updated general mistakes here and there.
L 07/18/2020 - 06:43:09: Successfully updated and installed "Updater".
L 07/18/2020 - 06:43:09: Reloading Updater plugin... updates will resume automatically.
L 07/18/2020 - 06:43:09: Update available for "Updater" (updater.smx). Current: 1.2.2 - Latest: 1.6.1-RC 5
L 07/18/2020 - 06:43:09:   [0]  Added new BETA (May not work) TF2 cheat detection for Infinite Noisemaker Spam. Since it is in BETA, it WON'T ban, only log! If no false positives are reported, it will perma ban in the future.
L 07/18/2020 - 06:43:09:   [1]  Added new backtrack patch method, 'Lock'. This patch method shouldn't affect laggy legit players much.
L 07/18/2020 - 06:43:09:   [2]  Added new ConVar 'lilac_max_ping_spec' (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds.
L 07/18/2020 - 06:43:09:   [3]  Added a delay for forwards so they won't get spammed to other plugins.
L 07/18/2020 - 06:43:09:   [4]  Updated how banning works through Sourcebans++/MaterialAdmin, it will now check if the native exists and not if the plugin by name is loaded.
L 07/18/2020 - 06:43:09:   [5]  Updated ConVar checker to be more basic and less CPU intensive.
L 07/18/2020 - 06:43:09:   [6]  Removed Anti-Duck-Delay/FastDuck's 1 week back length, it now perma bans.
L 07/18/2020 - 06:43:09:   [7]  Version 1.6.1-RC 5 Fixes:
L 07/18/2020 - 06:43:09:   [8]  Added noisemaker to lilac_set_ban_length command... Ops, forgot about that.
L 07/18/2020 - 06:43:09:   [9]  Updated general mistakes here and there.
L 07/18/2020 - 06:43:09: Update available for "[Lilac] Little Anti-Cheat" (lilac.smx). Current: 1.6.0-RC 4 - Latest: 1.6.1-RC 5
L 07/18/2020 - 06:43:09:   [0]  Added new BETA (May not work) TF2 cheat detection for Infinite Noisemaker Spam. Since it is in BETA, it WON'T ban, only log! If no false positives are reported, it will perma ban in the future.
L 07/18/2020 - 06:43:09:   [1]  Added new backtrack patch method, 'Lock'. This patch method shouldn't affect laggy legit players much.
L 07/18/2020 - 06:43:09:   [2]  Added new ConVar 'lilac_max_ping_spec' (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds.
L 07/18/2020 - 06:43:09:   [3]  Added a delay for forwards so they won't get spammed to other plugins.
L 07/18/2020 - 06:43:09:   [4]  Updated how banning works through Sourcebans++/MaterialAdmin, it will now check if the native exists and not if the plugin by name is loaded.
L 07/18/2020 - 06:43:09:   [5]  Updated ConVar checker to be more basic and less CPU intensive.
L 07/18/2020 - 06:43:09:   [6]  Removed Anti-Duck-Delay/FastDuck's 1 week back length, it now perma bans.
L 07/18/2020 - 06:43:09:   [7]  Version 1.6.1-RC 5 Fixes:
L 07/18/2020 - 06:43:09:   [8]  Added noisemaker to lilac_set_ban_length command... Ops, forgot about that.
L 07/18/2020 - 06:43:09:   [9]  Updated general mistakes here and there.
L 07/18/2020 - 06:43:21: Successfully updated and installed "Updater".
L 07/18/2020 - 06:43:21: Reloading Updater plugin... updates will resume automatically.
L 07/18/2020 - 06:43:21: SMC parsing error on line 0
L 07/18/2020 - 06:43:21:   [0]  URL: http://godtony.mooo.com/updater/updater.txt
L 07/18/2020 - 06:43:21:   [1]  ERROR: Line contained too many invalid tokens
L 07/18/2020 - 06:43:21: Update available for "[Lilac] Little Anti-Cheat" (lilac.smx). Current: 1.6.0-RC 4 - Latest: 1.6.1-RC 5
L 07/18/2020 - 06:43:21:   [0]  Added new BETA (May not work) TF2 cheat detection for Infinite Noisemaker Spam. Since it is in BETA, it WON'T ban, only log! If no false positives are reported, it will perma ban in the future.
L 07/18/2020 - 06:43:21:   [1]  Added new backtrack patch method, 'Lock'. This patch method shouldn't affect laggy legit players much.
L 07/18/2020 - 06:43:21:   [2]  Added new ConVar 'lilac_max_ping_spec' (Default 0), moves players with high ping into team spectator and warns them about potential kick after x many seconds.
L 07/18/2020 - 06:43:21:   [3]  Added a delay for forwards so they won't get spammed to other plugins.
L 07/18/2020 - 06:43:21:   [4]  Updated how banning works through Sourcebans++/MaterialAdmin, it will now check if the native exists and not if the plugin by name is loaded.
L 07/18/2020 - 06:43:21:   [5]  Updated ConVar checker to be more basic and less CPU intensive.
L 07/18/2020 - 06:43:21:   [6]  Removed Anti-Duck-Delay/FastDuck's 1 week back length, it now perma bans.
L 07/18/2020 - 06:43:21:   [7]  Version 1.6.1-RC 5 Fixes:
L 07/18/2020 - 06:43:21:   [8]  Added noisemaker to lilac_set_ban_length command... Ops, forgot about that.
L 07/18/2020 - 06:43:21:   [9]  Updated general mistakes here and there.
L 07/18/2020 - 06:43:24: Successfully updated and installed "[Lilac] Little Anti-Cheat".
```

After all it updated, because I see a new ban in my SourceBans++ :D
> [Little Anti-Cheat 1.6.1-RC 5] Aimbot entdeckt

**Comment by J-Tanzanite** [comment]
Awesome!

But also...
What did... I... Just see... ?!?!
( @-@) ... 

I might have to consider making my own updater plugin... What even...

**Comment by J-Tanzanite** [comment]
Version 1.6.0 is now official.

However, when I merged the changes, I made a mistake and updated the development version... Accidentally changing the update URL to the main branch.

I fixed it now, but thought I'd tell you in case it messed with your server.

**Comment by borzaka** [comment]
I'am not going to use the Updater plugin, because it's messing up some of the Updater enabled plugins:

```
43 <Bad Load> afk_manager4.smx
44 <Bad Load> smacbans-block.smx
```

After server restart:
```
Errors:
afk_manager4.smx: Unable to load plugin (bad header)
smacbans-block.smx: Unable to load plugin (bad header)
```

I will stick to the manual update until the official author releases a new version fixing all the issues.
And I'am still on the RC version:
`44 "[Lilac] Little Anti-Cheat" (1.6.1-RC 5) by J_Tanzanite`

It looks like the original version of the Updater plugin is unreliable. And I'am not going to use 3rd party fixes. I'am fine with the manual updates.

**Comment by J-Tanzanite** [comment]
Going to close this as auto update has been implemented.
It does seem like the auto updater has some weird bugs only affecting some people... I don't know why.
Anywhoo, issue resolved
