### ISSUE TITLE
german translation for restructured version

### ISSUE THREAD

**Issue by freakexeuLow** [J-Tanzanite/Little-Anti-Cheat#52]
I was bored and I improved a few things in german :3
[lilac.phrases.txt](https://github.com/J-Tanzanite/Little-Anti-Cheat/files/5699571/lilac.phrases.txt)

If more stuff is added, I will be translate it into German....Thank you for continuing to work on project 👍🏼

**Comment by J-Tanzanite** [comment]
Thank you :)

Do you wish to be credited for the translations?
Not just in the update, but in the official translations list?

**Comment by freakexeuLow** [comment]
> Thank you :)
> 
> Do you wish to be credited for the translations?
> Not just in the update, but in the official translations list?

Np :3

It is your decision :) I do not necessarily have to stand in it, i help gladly with some German translations

**Comment by J-Tanzanite** [comment]
Alright, the changes has been added.

I will add you to the translation credits once this version becomes the stable release. :)

**Comment by freakexeuLow** [comment]
> Alright, the changes has been added.
> 
> I will add you to the translation credits once this version becomes the stable release. :)

perfect and okay :3
