### ISSUE TITLE
Auto Shoot detection can be easily triggered.

### ISSUE THREAD

**Issue by pandaman09** [J-Tanzanite/Little-Anti-Cheat#6]
Auto Shoot detection can be easily triggered by changing your shoot button to the scroll wheel. It would appear that the scroll wheel input is only 1 frame long. This was tested in CS:GO on two different servers using the latest version

> 2020/05/05 15:02:47 [Version 1.5.0] {Name: "Panda" | SteamID: STEAM_1:1:33982761 | IP: } is suspected of using an aimbot (Detection: 2 | Delta: 0 | TotalDelta: 5 | Detected: Autoshoot).
> 2020/05/05 15:03:56 [Version 1.5.0] {Name: "Panda" | SteamID: STEAM_1:1:33982761 | IP: } is suspected of using an aimbot (Detection: 3 | Delta: 0 | TotalDelta: 2 | Detected: Autoshoot).
> 2020/05/05 15:04:58 [Version 1.5.0] {Name: "Panda" | SteamID: STEAM_1:1:33982761 | IP: } is suspected of using an aimbot (Detection: 4 | Delta: 0 | TotalDelta: 1 | Detected: Autoshoot).
> 2020/05/05 15:05:41 [Version 1.5.0] {Name: "Panda" | SteamID: STEAM_1:1:33982761 | IP: } is suspected of using an aimbot (Detection: 5 | Delta: 0 | TotalDelta: 4 | Detected: Autoshoot).
> 2020/05/05 15:05:41 [Version 1.5.0] {Name: "Panda" | SteamID: STEAM_1:1:33982761 | IP: } was banned for Aimbot.
> 	Pos={2557,-158,84}, Angles={-12.94214,172.69755,0.00000}, Map="de_inferno", Team={2}, Weapon="weapon_awp", Latency={Inc:0.000022,Out:0.048335}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.000000,Out:0.006835}, ConnectionTime={912.921875 seconds}, GameTime={774.195312 seconds}

**Comment by J-Tanzanite** [comment]
This is something I've already been aware of for nearly two years, ever since I originally wrote Lilac for TF2 back in 2018.

Due to the fact that you have to go out of your way to bind mwheeldown or mwheelup to shoot and kill people is so absurd and so unlikely to happen on any grand scale, it really doesn't warrant any concern.
Hence why I never removed it.

As far as I see it - when you have to go out of your way to do absurd actions to trigger a detection (Which no sensible people would realistically ever do) - then there really isn't a problem.

**Comment by pandaman09** [comment]
It might be worthwhile to add an option to disable autoshoot detection because of this. Otherwise it is too easy to get a false positive.

**Comment by J-Tanzanite** [comment]
Hmm, fair idea. Having the option to turn it off would be nice for server owners who rather not deal with the possibility of players deliberately making a mess of things. No matter how small the chances may be - it's a good idea.

I'll add a new ConVar tomorrow, "lilac_aimbot_autoshoot", which can be set to "0" to disable autoshoot detections all together.

**Comment by pandaman09** [comment]
Thank you! As a suggestion, you may also want to update the compile version to match the source provided.

**Comment by J-Tanzanite** [comment]
Alright, so one problem.

I never made it clear that GitHub is where I upload development stuff, and that the stable and latest version is found at AM (https://forums.alliedmods.net/showthread.php?t=321480).

This... Is just a dumb idea, and creates a mess of things. I should have known better...
From now on, all my latest changes will be in the development branch : https://github.com/J-Tanzanite/Little-Anti-Cheat/tree/development

You can find my latest changes there, and that includes the new ConVar as you suggested.

Unfortunately, although version 1.5.0 in the master branch is technically the latest stable branch, the actual stable release version is 1.3.0... On AM... This is going to be a bit of a mess.
So for now... The master branch is wrong, once the development of version 1.5.0 in the dev branch is done, the version in master will get updated and this mess will be sorted out.
