### ISSUE TITLE
Use a workflow to build instead of manually uploading binaries

### ISSUE THREAD

**Issue by BeepIsla** [J-Tanzanite/Little-Anti-Cheat#62]
Hey,

I don't use this plugin myself but I see you upload the plugin binary manually every time, typically you don't upload binaries directly and I assume you do this so users can just download the zip and drag & drop the whole thing into their SourceMod installation and it works right away without any additional moving of files and such.

Imo having binaries in the source code on Github is kind of ugly so I would suggest you instead only keep the source files and then bundle the binary in a zip and put it in the "Releases" section. You could fully automate this so every time you create a new release-tag the plugin automatically builds and then bundles it with all the other files. Its also great for catching compile errors for when you receive pull requests.

Maybe you already know about all this and there is a reason why you aren't using a workflow but I really recommend it.

---

If you choose to do this there is a nice [Github Action](https://github.com/rumblefrog/setup-sp) to make compiling SourceMod plugins using a workflow extremely easy.

**Comment by rlevet** [comment]
This is definitely better, but I never understand how to make Actions work, I don't understand a shit about .yml

**Comment by J-Tanzanite** [comment]
Oh yeah, I forgot to reply, sorry about that.

Anyway:
> Maybe you already know about all this and there is a reason why you aren't using a workflow

Nope... I'm just a noob :>

Joking aside, I do it so installation is easy for people. Plus, I don't find it that inconvenient.

> You could fully automate this so every time you create a new release-tag the plugin automatically builds and then bundles it with all the other files.

Didn't know that was possible, that sounds pretty neat. I should probably look into doing this, as for now tho, I'll just keep the current workflow.
Anyway, thanks for letting me know :)
