### ISSUE TITLE
No ban for bhop?

### ISSUE THREAD

**Issue by RusJJ** [J-Tanzanite/Little-Anti-Cheat#72]
Using Dev-12. It's detecting BHoppers. But there's no bans. Someone got banned for invalid cvars (i don't use other checks)

**Comment by J-Tanzanite** [comment]
The Bhop detection system was changed in the Beta version, people can now be detected of Bhop a few times before a ban is issued.
This is done to deal with unlucky players / false positives.

However, the Bhop system now has predefined configs, see `lilac_bhop` ConVar for more on this.
This means that you as a server owner can choose if you want the Bhop system to be more aggressive or more conservative.

lilac_bhop modes:
1. Reserved, automatically switches to 5 (Medium mode).
2. Reserved, automatically switches to 5 (Medium mode).
3. Custom (Do not use this!).
4. Low (Detects fewer Bhoppers, but are almost guarantied to be cheaters).
5. Medium (Default setting) (Detects Bhoppers, but can take time).
6. High (Detects Bhoppers fast, but has more false positives).

**Comment by RusJJ** [comment]
Still no ban:
2021/03/31 19:39:52 [Version 1.7.0-Dev 12] {Name: "Ne Itachi" | SteamID: STEAM_1:1:594814043 | IP: 62.217.184.248} is suspected of using Bhop (Detection: 4 | Bhops: 11 | JumpTicks: 11).
	Pos={658,-1043,2}, Angles={18.96359,100.11243,0.00000}, Map="workshop/2321790899/seek_q_house", Team={3}, Weapon="weapon_knife_karambit", Latency={Inc:0.000054,Out:0.015995}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.000000,Out:0.041423}, ConnectionTime={1012.364440 seconds}, GameTime={1213.640625 seconds}
2021/03/31 19:39:52 [Version 1.7.0-Dev 12] {Name: "Ne Itachi" | SteamID: STEAM_1:1:594814043 | IP: 62.217.184.248} was detected and banned for Bhop.
	Pos={658,-1043,2}, Angles={18.96359,100.11243,0.00000}, Map="workshop/2321790899/seek_q_house", Team={3}, Weapon="weapon_knife_karambit", Latency={Inc:0.000054,Out:0.015995}, Loss={Inc:0.000000,Out:0.000000}, Choke={Inc:0.000000,Out:0.041423}, ConnectionTime={1012.364440 seconds}, GameTime={1213.640625 seconds}

**Comment by J-Tanzanite** [comment]
Please refrain from showing player's IPs.

---

Anyway, so you aren't talking about Bhop not working, but materialadmin not working.
Did you use the precompiled plugin or compile it yourself?

Also, can you show me the output of this command: `lilac_ban_status`
I made this command to help diagnose issues related to banning.

**Comment by RusJJ** [comment]
Im using recompiled plugin. Still the same, except of Little-AntiCheat changed to LilAC.
Status:
![image](https://user-images.githubusercontent.com/8864329/113306898-3bad4080-930d-11eb-99df-8a73883622e9.png)

**Comment by J-Tanzanite** [comment]
I see, so you changed one thing and compiled it yourself. Ok.

Assuming you didn't change anything else, the fact that we don't get warnings about includes is a good sign.
And MA is loaded, native is ready and ConVar is set to use it.
So banning through MA should work fine.

Are you sure MA is setup correctly?

Also, version 1.7.0-Dev 13 was released yesterday. It hasn't changed anything in relation to banning, but thought I'd let you know anyway

**Comment by RusJJ** [comment]
Of course! That worked on 1.6.3. Latest ban: 15 March. Changed plugin at 17 March, nothing changed except of LilAC.

**Comment by J-Tanzanite** [comment]
Hmm, well that would be pretty strange, as I didn't change how banning works...
I did change how the Bhop detection works... hmmm...
**Remembers**
Oh right! I forgot!

I removed banning for Bhop since I changed how Bhop detection works, and I didn't want people who tested it out to ban innocent people in case there was a bug or an issue.
Right, that's what it was!

I haven't gotten complaints about the new Bhop detection system, and in my testing, it works.
So I should just re-enable banning... Thanks for reminding me I guess :'D 
(How did I forget I removed that for testing purposes lmao)

I'll release version 1.7.0-Dev 14 today, which will have banning for Bhop re-enabled again.

**Comment by J-Tanzanite** [comment]
Alright, version 1.7.0-Dev 14 is out, and has a fix for this issue.
I'll leave this issue open for a few days in case it doesn't work :)

**Comment by RusJJ** [comment]
Thanks anyway! Already "merged" by my hands into "my" version (i dont wanna Ctrl+F all texts ;D)

**Comment by RusJJ** [comment]
Ban works, got my "legit" player banned second time while using LilAC. Thanks! 😂

**Comment by J-Tanzanite** [comment]
I didn't know what hugerain was, so had to ask someone.
It's an external Bhop cheat? Which people pay for? (Certainly hope people don't pay for Bhop cheats, that's just sad)

**Comment by RusJJ** [comment]
Well idk much too. I think its paid but can be found for free. Maybe external.

**Comment by RusJJ** [comment]
Well idk much too. I think its paid but can be found for free. Maybe external.

**Comment by J-Tanzanite** [comment]
Paying for only Bhop lmao :'D

Anyway, great to hear it's all working well and banning works now.
I'll close this since this issue has been resolved.
If anything else comes up, don't hesitate to open another issue :)
