### ISSUE TITLE
Add people who translated

### ISSUE THREAD

**Issue by Tiagoquix** [J-Tanzanite/Little-Anti-Cheat#79]
The list of "Translation authors" [here](https://forums.alliedmods.net/showthread.php?t=321480) is outdated when compared to [this list](https://github.com/J-Tanzanite/Little-Anti-Cheat#current-languages-supported). Can you please update your SM's topic? Thanks!

**Comment by J-Tanzanite** [comment]
Yeah, it's something I've been meaning to do, but have been putting it off for a while.
That post needs more than just a translation-credits update, but huge overhaul in general.

One thing I also need to do is make a FAQ.
General style is also bad, and it's a little cluttered.
But yeah, I'll get to it.

**Comment by J-Tanzanite** [comment]
I've updated the list, I still need to update the post further, but done :)
