### ISSUE TITLE
[Typo] "kick_ban_genetic" In translations files

### ISSUE THREAD

**Issue by J-Tanzanite** [J-Tanzanite/Little-Anti-Cheat#8]
Yeah, I'm raising an issue just to make it clear that I am aware of this; before anyone else thinks about correcting it or asking me to do so.

# And I **REFUSE** to fix this typo!

I'm concerned that by fixing the typo in the sourcecode and in the translations,\
some people when they upgrade to a newer version of Little Anti-Cheat will ONLY install the newer binary, and not also install the new translations...

This would cause **ERRORS** in Sourcemod when it tries to access translations that don't exist.
>[SM] Exception reported: Language phrase "kick_ban_generic" not found

And instead of telling those people to install the new translations files (And everyone else) It's literally better to leave it as is.\
It's not a major spelling mistake, and it doesn't affect server owners one bit, which is what matters.

Had the spelling mistake been in the translations itself, it would be fine to fix it, as it wouldn't ever cause any errors to arise.

### So yes, this typo will NOT get fixed, and it shouldn't be either!

**Comment by borzaka** [comment]
Maybe include in the next release note: update the translation files as well.

**Comment by J-Tanzanite** [comment]
I'm afraid that wouldn't work.
Sure, the vast majority of people would update the translations files and not have any issues.

But if there is one thing I've learnt over the years, it's that some people (very very few) are bad at following instructions.
Not everyone speaks English too well either.
Fixing this typo is unnecessary, it just opens the door for mistakes to happen.
It's literally better to leave it as is, and not create unnecessary potential problems for some people.

---

That said, we **have** to update the translations files regardless now, since the Anti-Duck-Delay detection was added.
So I guess in version 1.6.0, I could fix this issue.

So you are right!
Due to the big update, translations from version 1.5.1 (and older) are out-of-date and incompatible with the newer version anyway, fixing this wouldn't cause any unnecessary risks because they are already incompatible.

If people try to use version 1.6.0 with older translations, I don't mind telling them to update the translations files. As it's only reasonable now.
