### ISSUE TITLE
Support NoMoreRoomInHell

### ISSUE THREAD

**Issue by Yamiru** [J-Tanzanite/Little-Anti-Cheat#82]
hello, can you add support to game NoMoreRoomInHell thank you .)

**Comment by J-Tanzanite** [comment]
Sorry for my late reply.

Anyway, I don't know too much about the game.
Having taken a little look at it, I don't quite see how cheating has a huge effect?

That said, Lilac does work in L4D&L4D2, and I assume it should work in NMRIH as well.
I haven't tested that game, so you would have to test it and report back if it works or not.

**Comment by Yamiru** [comment]
np I test it :)
