### ISSUE TITLE
Make a database system

### ISSUE THREAD

**Issue by azalty** [J-Tanzanite/Little-Anti-Cheat#83]
https://forums.alliedmods.net/showpost.php?p=2740499&postcount=293

This is mainly for me to remember to do it, list changes or see if anyone wants to help, propose changes or do other things.

**Comment by J-Tanzanite** [comment]
Your database PR has been accepted, great work! ^-^

**Comment by azalty** [comment]
> Your database PR has been accepted, great work! ^-^

Thanks! I finally did it, after all that time :)
Worst thing is that it didn't even took me that long (shame on me)
