### ISSUE TITLE
AimBot Detection | False Positive

### ISSUE THREAD

**Issue by crashzk** [J-Tanzanite/Little-Anti-Cheat#86]
I took a ban for **AimBot** but it was a false positive.

How am I sure it was a false positive? A player of ours likes to use fake binds for spinbot, why is that? I do not know.

After that I tested it myself:
```
alias "+spinbot" "sensitivity 10; m_yaw 666"
```
```
alias "-spinbot" "sensitivity YOUR_SENS; m_yaw 0.022"
```
```
bind "mouse4" "+spinbot"
```
**YOUR_SENS = Your sensitivity in the game.**

After some time playing and killing the players I took the ban. To use is simple, always before shooting, press the **`+spinbot`** bind, in the example above **`mouse4`**, then press **mouse4 + mouse1** to shoot.

My question would be, some way to correct this, improve the detection system of AimBot, or would that not be possible?

**Comment by J-Tanzanite** [comment]
Seems like more people are testing out those commands to mimic cheaters...
And getting banned... That's pretty funny :')

I pretty much answered it here: https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/84

Fact of the matter is that, if a player has to go out of their way to do something stupid (to look like a cheater) by using special commands or scripts, and they get banned - well, then they got what they asked for. :| 

This isn't something that can happen to a legit player by accident, it's a conscious thing you have to do to mimic a spinbot... I mean... There's nothing to fix. It detected inhuman/highly abnormal aiming upon killing someone.
And those commands will often make you do ~180 degree turns, which is something some cheats actually do...

---

As for whether or not it's possible to prevent this? No.

You see, if I were to add any code to check for high sensitivity - then cheats could lie and pretend to have high sensitivity - bypassing the aimbot check.

So from the server side, it's impossible to tell if a player has a high sens or if a cheat is faking it.
And adding a "warning/suspicion" is useless, as then cheaters would have also bypassed it.

---

Honestly, this isn't something I would worry about.
If someone gets banned for using these commands to try to mimic an aimbot, then it's their own fault.
They wanted to look like a cheater, to make people think they were cheating... Obviously you were going to get banned; if not by Lilac, then likely by an admin.

Legit players who play normally aren't going to get false positives for this, even those with with normal high sensitivities.

**Comment by crashzk** [comment]
I thought about that too, thanks in any case.
