### ISSUE TITLE
What is anti duck delay ?

### ISSUE THREAD

**Issue by vegeta1241** [J-Tanzanite/Little-Anti-Cheat#87]
Hello, What is anti duck delay ?

Someone was spec for long time on my serv and it was banned for anti duck delay. It is normal ?

**Comment by azalty** [comment]
All anti duck delay detections are 100% accurate

This cheat method is done by sending a key input that isn't possible for a legit player.
To trigger this detection you need to have an injected cheat, so make sure these detections are permanent.

Don't even try to unban them :)

**Comment by J-Tanzanite** [comment]
What Azalty is saying here is correct.

Anti-Duck-Delay (Also known as FastDuck) is the most common cheat feature detected by Lilac in CS:GO.
It is completely normal to see bans for Anti-Duck-Delay, you don't have to worry about it. :)

**Comment by J-Tanzanite** [comment]
Closing this as this has been answered and no further replies have been made.

If you have another question or problem, feel free to open a new issue :)
