### ISSUE TITLE
"longjump"?

### ISSUE THREAD

**Issue by RusJJ** [J-Tanzanite/Little-Anti-Cheat#88]
Hi there! Got a few losers with that weirdo cheat that just pushes you forward on a jump. Is there any checks for this in LilAC?

**Comment by azalty** [comment]
That's called an autostrafer and I'm pretty sure lilac doesn't check for that. You should add a bhop/movement specific anticheat, there are quite some that are good and free on alliedmodders

**Comment by J-Tanzanite** [comment]
Sorry for the slow reply.
I might have to make a PSA about this (I am currently in the process of moving, and will be slightly less available than usual).

Anyway, I wasn't sure what you meant until Azalty cleared it up, assuming Azalty guessed right.

Autostrafe used to be in Lilac prior to the public release, back when Lilac was private.
But it hasn't been added back yet.

What Azalty is saying is correct, there are several good autostrafe detectors out there that you can use (Not that I have ever used any of them).

**Comment by RusJJ** [comment]
A cheater just jumping forward. Without any moving to left/right. Is it autostrafe @azalty?

**Comment by J-Tanzanite** [comment]
> A cheater just jumping forward. Without any moving to left/right. Is it autostrafe @azalty?

Well, it *might* be a cheat, but you **shouldn't** ban manually for these things if you aren't sure...
In fact, I don't recommend manually banning players you suspect of using Autostrafe at all; it's better left to plugins to detect.

Since I've cheated before, I can tell you that there are "silent" Autostrafes, that means you can look straight ahead without looking left or right and still gain speed.
However, leave it to plugins to detect, that's my recommendation.

Hope Azalty doesn't rip me a new one for saying that ;)

**Comment by azalty** [comment]
> A cheater just jumping forward. Without any moving to left/right. Is it autostrafe @azalty?

Silent autostrafer, yes, it is a thing 👀

**Comment by azalty** [comment]
> Well, it _might_ be a cheat, but you **shouldn't** ban manually for these things if you aren't sure...
> In fact, I don't recommend manually banning players you suspect of using Autostrafe at all; it's better left to plugins to detect.

This ^^

> Hope Azalty doesn't rip me a new one for saying that ;)

You are correct :) Can't exactly get the meaning of ur phrase since i'm not a native speaker 👀

**Comment by J-Tanzanite** [comment]
"Rip me a new one" basically means yelling at me that I am wrong ;)

**Comment by azalty** [comment]
> "Rip me a new one" basically means yelling at me that I am wrong ;)

Hey, I didn't yell at you! (in this issue at least 😏)
